### ISSUE TITLE
Google Calendar API Bug

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1012]
Google Calendar API Bug
#### Environment details
python 3.8.3
google-cloud==0.34.0
#### Code example
```py
import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'Timer_Hello_Layered/creds.json'        
        
service = build('calendar', 'v3', credentials=accessToken, cache_discovery=False) 
        
        event = {
        'summary': 'Test',
        'location': 'At home',
        'description': 'A chance to hear more about Google\'s developer products.',
        'start': {
            'dateTime': '2020-07-29T12:12:10',
            'timeZone': 'America/Los_Angeles',
        },
        'end': {
            'dateTime': '2020-07-29T12:32:47',
            'timeZone': 'America/Los_Angeles',
        }
        }
        event = service.events().insert(calendarId='primary', body=event).execute()

```
#### Error:
```
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch.py", line 118, in dispatch
    output = self.__dispatch_request(handler_input)  # type: Union[Output, None]
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch.py", line 182, in __dispatch_request
    output = supported_handler_adapter.execute(
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch_components/request_components.py", line 437, in execute
    return handler.handle(handler_input)
  File "/var/task/lambda_function.py", line 249, in handle
    service = build('calendar', 'v3', credentials=accessToken, cache_discovery=False)
  File "/opt/python/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/googleapiclient/discovery.py", line 272, in build
    return build_from_document(
  File "/opt/python/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/googleapiclient/discovery.py", line 497, in build_from_document
    http = _auth.authorized_http(credentials)
  File "/opt/python/lib/python3.8/site-packages/googleapiclient/_auth.py", line 104, in authorized_http
    return credentials.authorize(build_http())
AttributeError: 'str' object has no attribute 'authorize'END RequestId
```
Not sure why i am getting this error in my lambda despite adding the os path.

**Comment by busunkim96** [comment]
Hi @danieldhz,

How are you setting `accessToken`?

**Comment by danieldhz** [comment]
I am building an Alexa skill. Thereby, I used the boilerplate code provided to retrieve user's accesToken.

**Comment by busunkim96** [comment]
I see that `discovery.build()` gets an `accessToken`, but it's unclear to me where it's coming from in the code. Would you mind copy/pasting the boilerplate you're using to fetch the token?

```py
import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'Timer_Hello_Layered/creds.json'        

# where is accessToken set?
service = build('calendar', 'v3', credentials=accessToken, cache_discovery=False) 
```

If `GOOGLE_APPLICATION_CREDENTIALS` is set to a service account with permissions you may not need to pass `credentials`. Could you try this instead?

```py
service = build('calendar', 'v3', cache_discovery=False) 
```

**Comment by danieldhz** [comment]
@busunkim96 You killed it. Just to make logical sense to me. Where does the accessToken get inputted then if its not inserted in the build().
#### Full Code:
```
class GoogleIntentHandler(AbstractRequestHandler):
    def can_handle(self, handler_input):
        return ask_utils.is_intent_name("GoogleIntent")(handler_input)
    def handle(self, handler_input):
        accessToken = handler_input.request_envelope.context.system.user.access_token
        persistence_attr = handler_input.attributes_manager.persistent_attributes
        persistence_attr['accessToken'] = accessToken
        handler_input.attributes_manager.save_persistent_attributes()
          
        #For retrieving the access token
        persistence_attr = handler_input.attributes_manager.persistent_attributes
        accessToken = persistence_attr['accessToken']
        logger.info(f'access token : {accessToken}')
        service = build('calendar', 'v3', cache_discovery=False) 
        
        event = {
        'summary': 'Test',
        'location': 'At home',
        'description': 'A chance to hear more about Google\'s developer products.',
        'start': {
            'dateTime': '2020-07-29T12:12:10',
            'timeZone': 'America/Los_Angeles',
        },
        'end': {
            'dateTime': '2020-07-29T12:32:47',
            'timeZone': 'America/Los_Angeles',
        }
        }
        #check if you can call a color via the api too
        event = service.events().insert(calendarId='primary', body=event).execute()
```

**Comment by busunkim96** [comment]
@danieldhz There is an implicit auth flow that will be used instead.

 https://github.com/googleapis/google-api-python-client/blob/5028fe76c8075c6594b1999074f91eed7f7dd329/googleapiclient/discovery.py#L485-L489. 

The code looks for credentials in your environment (in this case it will use what's provided in `GOOGLE_APPLICATION_CREDENTIALS`).

**Comment by danieldhz** [comment]
@busunkim96 Got it. But the credentials that was passed into `GOOGLE_APPLICATION_CREDENTIALS` was my credentials. Would `GOOGLE_APPLICATION_CREDENTIALS` be updated to someone else credential once they use the app & get redirected?

**Comment by busunkim96** [comment]
No, if you need to use user credentials you should use the user oauth2 flow. The [calendar quickstart](https://developers.google.com/calendar/quickstart/python) shows how to do that.

**Comment by danieldhz** [comment]
@busunkim96 so I have to add back credentials=accessToken? which then causes the error. I don't see much difference between the quickstart & my code aside saving access token.

**Comment by busunkim96** [comment]
The error message seems to suggest whatever you are passing for `credentials` is invalid. It looks like it's a string instead of a `google.auth.credentials` object.

```
File "/opt/python/lib/python3.8/site-packages/googleapiclient/_auth.py", line 104, in authorized_http
    return credentials.authorize(build_http())
AttributeError: 'str' object has no attribute 'authorize'END RequestId
```

The quickstart shows how to fetch a credential object using the auth library.

**Comment by danieldhz** [comment]
@busunkim96 Got it. So since I believe I have a service account where users interact with, you recommended me to save the access token in the InstalledAppFlow over the pickle right?

**Comment by danieldhz** [comment]
Hi @busunkim96 . I looked at the quickstart code. I believe this will be the code to work with Alexa:
```
        creds = None
               
        # The file token.pickle stores the user's access and refresh tokens, and is
        # created automatically when the authorization flow completes for the first
        # time.
        if os.path.exists('token.pickle'):
            with open('token.pickle', 'rb') as token:
                creds = pickle.load(token)
        # If there are no (valid) credentials available, let the user log in.
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                creds = handler_input.request_envelope.context.system.user.access_token
            # Save the credentials for the next run
            with open('token.pickle', 'wb') as token:
                pickle.dump(creds, token)

        service = build('calendar', 'v3', credentials=creds) 
```

**Comment by parthea** [comment]
Hi @DaniyalDhz ,

I'm going to close this issue as guidance was provided in #1032. If you're still having trouble please re-open this issue with additional information.
