### ISSUE TITLE
TypeError: default() got an unexpected keyword argument 'quota_project_id'

### ISSUE THREAD

**Issue by aginpatrick** [googleapis/google-api-python-client#1069]
#### Environment details

  - OS type and version: Mac OS High Sierra 10.13.1
  - Python version: 3.7.6
  - pip version: 19.2.3
  - `google-api-python-client` version: 1.12.3

#### Steps to reproduce

in Python run the following code

#### Code example

```python
import googleapiclient.discovery 
googleapiclient.discovery.build('ml', 'v1')
```

#### Stack trace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/.virtualenvs/myenv/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/me/.virtualenvs/myenv/lib/python3.7/site-packages/googleapiclient/discovery.py", line 288, in build
    adc_key_path=adc_key_path,
  File "/Users/me/.virtualenvs/myenv/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/me/.virtualenvs/myenv/lib/python3.7/site-packages/googleapiclient/discovery.py", line 529, in build_from_document
    quota_project_id=client_options.quota_project_id,
  File "/Users/me/.virtualenvs/myenv/lib/python3.7/site-packages/googleapiclient/_auth.py", line 54, in default_credentials
    credentials, _ = google.auth.default(scopes=scopes, quota_project_id=quota_project_id)
TypeError: default() got an unexpected keyword argument 'quota_project_id'

```

Thanks!

**Comment by christianversloot** [comment]
Perhaps `pip install --upgrade google-auth`

For me, it upgraded:

```
Installing collected packages: google-auth
  Attempting uninstall: google-auth
    Found existing installation: google-auth 1.17.2
    Uninstalling google-auth-1.17.2:
      Successfully uninstalled google-auth-1.17.2
Successfully installed google-auth-1.22.1
```

**Comment by aginpatrick** [comment]
Thanks @christianversloot it works. Actually I had tried to upgrade oauth2client and google-api-client but I forgot to try upgrading also google-auth.  I also noticed that reversing to google-api-python-client 1.8.4 also works. Thanks again.
