### ISSUE TITLE
Cannot get credentials to connect to google API

### ISSUE THREAD

**Issue by VivekGrimm** [googleapis/google-api-python-client#1091]
Hi,

I couldn't find any information on this problem, if I should also post somewhere else, please let me know.

What I am trying to do is/should be super simple: I want to read data from a google spreadsheets. I followed this: https://developers.google.com/sheets/api/quickstart/python
I created a desktop app (when clicking on "enable the google sheets api", downloaded the credentials.json file, copied the quickstart, etc...

When running the quickstart though, it fails on `flow.run_local_server(port=0)`
It does redirect me to a browser, asks me to choose an account the "allow" the app. When that flow is done, there is a message in the browser saying it's done and the window can be closed.

However, the script crashes with this error:
```
Traceback (most recent call last):
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/vigri/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/vigri/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/vigri/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/vigri/dev/other/fi_dashboard/DAO/GoogleSheetsConnection.py", line 47, in <module>
    get_data_from_sheets('TransactionData')
  File "/Users/vigri/dev/other/fi_dashboard/DAO/GoogleSheetsConnection.py", line 41, in get_data_from_sheets
    sheet = get_sheets()
  File "/Users/vigri/dev/other/fi_dashboard/DAO/GoogleSheetsConnection.py", line 28, in get_sheets
    creds = flow.run_local_server(port=0)
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 474, in run_local_server
    self.fetch_token(authorization_response=authorization_response)
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 288, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 336, in fetch_token
    r = self.request(
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/vigri/opt/anaconda3/envs/fi-dashboard/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
```

I am using a conda environment.
- Python 3.8.2
- google-api-core           1.23.0
- google-api-python-client  1.12.5
- google-auth               1.23.0
- google-auth-httplib2      0.0.4
- google-auth-oauthlib      0.4.2
- googleapis-common-protos  1.52.0
- httplib2                  0.18.1

Could you help me out to figure out what's wrong?
Any other information I should add?

**Comment by parthea** [comment]
Hey @ VivekGrimm,

This issue sounds similar to the one described [here](https://github.com/googleworkspace/python-samples/issues/107)  . It's posisble that you have a bad certificate configuration on your machine. Please could you check [this comment](https://github.com/googleworkspace/python-samples/issues/107#issuecomment-507708727) (and workaround), then report back?

**Comment by VivekGrimm** [comment]
Hi @parthea,
Thanks for the reply. I tried what they mentioned but I still get the same error.
I added this code: 
```
_create_unverified_https_context = ssl._create_unverified_context
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
    getattr(ssl, '_create_unverified_context', None)): 
    ssl._create_default_https_context = ssl._create_unverified_context
```

I also tried to follow some other comments about installing certifi, setting env variables:
```
CERT_PATH=$(python -m certifi)
export SSL_CERT_FILE=${CERT_PATH}
export REQUESTS_CA_BUNDLE=${CERT_PATH}
```
But no success :/

Is there a way to check that  it is an issue with the certificates?

**Comment by parthea** [comment]
In terminal try:

```
openssl s_client -connect google.com:443
```
I'm curious if you see the same error message as the one you reported in the original post. The error message `unable to get local issuer certificate` was also discussed [here](https://stackoverflow.com/questions/11548336/openssl-verify-return-code-20-unable-to-get-local-issuer-certificate), and my initial thought is that it will be quicker to troubleshoot using `openssl`.

You could try following suggestion [here](https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests-in-python/57466119#57466119). Let me know if you're still stuck after this step. A note of caution: Please don't paste sensitive information in GitHub. Instead you could include a snippet of any error messages that you see.

**Comment by VivekGrimm** [comment]
Hi,

When I try the openssl s_client command, I get the same error
```
SSL handshake has read 4754 bytes and written 438 bytes
Verification error: unable to get local issuer certificate
```
Let me know if there is something specific that is valuable in the trace.
I followed both links and tried to specify -CApath and -CAfile pointing to the cacert.pem file in the certifi directory. Both lead to the same error.

I also tried to copy the certificates manually from the account.google link (that I get directed to when running the quickstart script) to the certificate file. I added all 3 levels (in the hierarchy). Then tried again running the script, and tried the terminal command too. But they all lead to the same error :/

**Comment by parthea** [comment]
Are you able to run the code in the OP on a different machine to determine whether the issue is related to your network or the specific machine you're using? Since the issue is reproducible with `openssl`, I'm afraid that this is outside of the scope of what I can troubleshoot in this repo. My initial thought is it may be a better question for StackOverflow for `openssl` experts. It would be great if you could add the StackOverflow here in case any users run into the same issue. I'm going to close off this issue but please keep us posted on your progress!
