### ISSUE TITLE
oogle.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [googleapis/google-api-python-client#1134]
Hi
I am trying with 

import os 
from google.cloud import storage
os.environ["GCLOUD_PROJECT"]=project-name
file_path = 'outputs/mixture1/meta-adapter/task-emb/mix1-meta-task-emb-new-lr-3e-03/eval_results.json'
storage_client = storage.Client()
bucket = storage_client.get_bucket(bucket-name)

and I get 
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    bucket = storage_client.get_bucket("gs://ruse-xcloud-bucket")
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/cloud/storage/client.py", line 361, in get_bucket
    if_metageneration_not_match=if_metageneration_not_match,
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/cloud/storage/bucket.py", line 936, in reload
    if_metageneration_not_match=if_metageneration_not_match,
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/cloud/storage/_helpers.py", line 210, in reload
    retry=DEFAULT_RETRY,
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 63, in api_request
    return call()
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/cloud/_http.py", line 434, in api_request
    timeout=timeout,
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/cloud/_http.py", line 292, in _make_request
    method, url, headers, data, target_object, timeout=timeout
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/cloud/_http.py", line 330, in _do_request
    url=url, method=method, headers=headers, data=data, timeout=timeout
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/auth/transport/requests.py", line 460, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/oauth2/credentials.py", line 206, in refresh
    self._scopes,
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/oauth2/_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/usr/local/google/home/rabeeh/anaconda3/envs/internship/lib/python3.7/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')

thanks

**Comment by parthea** [comment]
Hi @rabeehkarimimahabadi ,

Please post your question in the `python-storage` repo [here](https://github.com/googleapis/python-storage) as this repo is for `googleapiclient` not `google.cloud.storage`.
