### ISSUE TITLE
TimeoutError: [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by senRsl** [googleapis/google-api-python-client#1158]
log:
```
(venv) SENRSL:blog senrsl$ python blogger/blogger.py --logging_level=DEBUG --noauth_local_webserver
/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access blogger.dat: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?client_id=888-999.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fblogger&access_type=offline&response_type=code

Enter verification code: 000
Traceback (most recent call last):
  File "/Users/senrsl/temp/blog/blogger/blogger.py", line 84, in <module>
    main(sys.argv)
  File "/Users/senrsl/temp/blog/blogger/blogger.py", line 47, in main
    service, flags = sample_tools.init(
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/googleapiclient/sample_tools.py", line 98, in init
    credentials = tools.run_flow(flow, storage, flags)
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/oauth2client/tools.py", line 243, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/oauth2client/client.py", line 2053, in step2_exchange
    resp, content = transport.request(
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/oauth2client/transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/httplib2/__init__.py", line 1985, in request
    (response, content) = self._request(
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/httplib2/__init__.py", line 1650, in _request
    (response, content) = self._conn_request(
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/httplib2/__init__.py", line 1557, in _conn_request
    conn.connect()
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/httplib2/__init__.py", line 1391, in connect
    raise socket_err
  File "/Users/senrsl/temp/blog/venv/lib/python3.9/site-packages/httplib2/__init__.py", line 1324, in connect
    sock.connect((self.host, self.port))
TimeoutError: [Errno 60] Operation timed out
(venv) SENRSL:blog senrsl$ 
```

Is this only a network problem? Or what do I need to do after entering the verification code?

Thx.

**Comment by busunkim96** [comment]
Yes, it looks like a network issue from the error message. Can you show us a bit of your code?

**Comment by senRsl** [comment]
The code in the sample I copied, https://github.com/googleapis/google-api-python-client/tree/master/samples/blogger, has been running timeout, it seems to be a network problem in mainland China.

```
  # Authenticate and construct service.
  service, flags = sample_tools.init(
      argv, 'blogger', 'v3', __doc__, __file__,
      scope='https://www.googleapis.com/auth/blogger') 
```

Is there any other way to get  “service”？
Thanks for reply。

**Comment by senRsl** [comment]
Thank you very much. 
It has been timed out yesterday. 
It turns out that I forgot to hang the proxy for the terminal, so I can’t access google.

Thanks again for your confirmation.
