### ISSUE TITLE
HelloAnalytics  

### ISSUE THREAD

**Issue by shikunshowyou** [googleapis/google-api-python-client#1172]
```
from googleapiclient.discovery import build
from google.oauth2.service_account import Credentials

def initialize_analyticsreporting():
    """Initializes an Analytics Reporting API V4 service object.

    Returns:
      An authorized Analytics Reporting API V4 service object.
    """
    credentials = Credentials.from_service_account_file(
        KEY_FILE_LOCATION, scopes=SCOPES)

    # Build the service object.
    analytics = build('analyticsreporting', 'v4', credentials=credentials)

    return analytics
```

when I run python HelloAnalytics.py always alert this error, how to fix it?

```
Traceback (most recent call last):
  File "/Users/show/workspace/ajmall/bigdata_etl/scripts/HelloAnalytics.py", line 78, in <module>
    main()
  File "/Users/show/workspace/ajmall/bigdata_etl/scripts/HelloAnalytics.py", line 72, in main
    analytics = initialize_analyticsreporting()
  File "/Users/show/workspace/ajmall/bigdata_etl/scripts/HelloAnalytics.py", line 21, in initialize_analyticsreporting
    analytics = build('analyticsreporting', 'v4', credentials=credentials)
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/googleapiclient/discovery.py", line 270, in build
    content = _retrieve_discovery_doc(
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/googleapiclient/discovery.py", line 376, in _retrieve_discovery_doc
    resp, content = req.execute(num_retries=num_retries)
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/googleapiclient/http.py", line 900, in execute
    resp, content = _retry_request(
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/googleapiclient/http.py", line 204, in _retry_request
    raise exception
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/httplib2/__init__.py", line 1985, in request
    (response, content) = self._request(
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/httplib2/__init__.py", line 1650, in _request
    (response, content) = self._conn_request(
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/httplib2/__init__.py", line 1557, in _conn_request
    conn.connect()
  File "/Users/show/workspace/ajmall/bigdata_etl/venv/lib/python3.8/site-packages/httplib2/__init__.py", line 1324, in connect
    sock.connect((self.host, self.port))
socket.timeout: timed out
```

**Comment by parthea** [comment]
Hi  @shikunshowyou, I'm not able to reproduce the problem. It appears to be a network problem. 

Please check the following:

-  Can you try to see if you can visit [this](https://www.googleapis.com/discovery/v1/apis/) page in your browser? 
-  Can you try running the following command in terminal and post the output?  
`curl https://www.googleapis.com/discovery/v1/apis/`
- Are you using a proxy?

**Comment by parthea** [comment]
Hi @shikunshowyou,

I'm going to close off this issue but please feel free to re-open it with more information.
