### ISSUE TITLE
AdsDataHub v1 support

### ISSUE THREAD

**Issue by jdiazdiv** [googleapis/google-api-python-client#1248]
I cannot use AdsDataHub v1 API. The code I am trying to run is the one in the official [docs](https://developers.google.com/ads-data-hub/guides/quickstart-api#send_a_sample_request):

#### Environment details

  - OS type and version: MacOS
  - Python version: 3.8.1
  - pip version: 21.0.1
  - `google-api-python-client` version: 2.0.2

#### Code example

```python
"""This sample shows how to retrieve all accounts associated with the user.

For the program to execute successfully, ensure that you run it using Python 3.
"""

from __future__ import print_function
import json
from google_auth_oauthlib import flow
from googleapiclient.discovery import build

appflow = flow.InstalledAppFlow.from_client_secrets_file(
    # Replace client_secrets.json with your own client secret file.
    'credentials/client_secrets.json',
    scopes=['https://www.googleapis.com/auth/adsdatahub'])
appflow.run_local_server()
credentials = appflow.credentials

import os
developer_key = os.getenv('ADH_DEVELOPER_KEY')

service = build('AdsDataHub', 'v1', credentials=credentials,
                developerKey=developer_key)


def pprint(x):
  print(json.dumps(x, sort_keys=True, indent=4))


customer_name = input('Customer name (e.g. "customer/123"): ').strip()
pprint(service.customers().analysisQueries().list(parent
                                                  =customer_name).execute())
```

#### Stack trace
```
Traceback (most recent call last):
  File "prueba2.py", line 22, in <module>
    service = build('AdsDataHub', 'v1', credentials=credentials,
  File "/Users/juandiaz/OneDrive - Merkle Inc/Clientes/Mapfre DCND/Ads Data Hub/command-center/ADH_API/venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/juandiaz/OneDrive - Merkle Inc/Clientes/Mapfre DCND/Ads Data Hub/command-center/ADH_API/venv/lib/python3.8/site-packages/googleapiclient/discovery.py", line 273, in build
    content = _retrieve_discovery_doc(
  File "/Users/juandiaz/OneDrive - Merkle Inc/Clientes/Mapfre DCND/Ads Data Hub/command-center/ADH_API/venv/lib/python3.8/site-packages/googleapiclient/discovery.py", line 387, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: AdsDataHub  version: v1
```

**Comment by busunkim96** [comment]
Hi @jdiazdiv,

Please see #1225 for details on accessing private APIs.

This believe this will work for building the client:

```py
from googleapiclient import discovery

client = discovery.build(
    'AdsDataHub',
    'v1',
    credentials=credentials,
    developerKey=developer_key,
    discoveryServiceUrl='https://adsdatahub.googleapis.com/$discovery/rest?version=v1',
    static_discovery=False
)
```

**Comment by jdiazdiv** [comment]
Thank you @busunkim96 , it works!
