### ISSUE TITLE
The `sharedWithMe` request parameter is being processed incorrectly 

### ISSUE THREAD

**Issue by mef1stofel** [googleapis/google-api-python-client#1257]
I tried to get files from Google Drive that owned by user, not shared with him.

#### Environment details

  - OS type and version: Ubuntu 20.04.1 LTS
  - Python version: Python 3.8.5
  - pip version:  19.0.3
  - `google-api-python-client` version:  2.0.2

#### Code example

```python
import google.oauth2.credentials
from googleapiclient.discovery import build

cred = ...  # credentials google.oauth2.credentials.Credentials
service = build('drive', 'v3', credentials=cred)

# This works well
service.files().list(
    pageSize=999,
    fields='nextPageToken, files(id, name, mimeType, parents, modifiedTime, size, ownedByMe)',
    q='sharedWithMe'
).execute()

# But I need to get files Not shared with the user and use operations =, != from here https://developers.google.com/drive/api/v3/ref-search-terms I got an error
service.files().list(
    pageSize=999,
    fields='nextPageToken, files(id, name, mimeType, parents, modifiedTime, size, ownedByMe)',
    q='sharedWithMe=false'
).execute()
```

#### Stack trace
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/serhio/Projects/google_drive/venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/serhio/Projects/google_drive/venv/lib/python3.8/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/drive/v3/files?pageSize=999&fields=nextPageToken%2C+files%28id%2C+name%2C+mimeType%2C+parents%2C+modifiedTime%2C+size%2C+ownedByMe%29&q=sharedWithMe+%21%3D+true&alt=json returned "Invalid Value". Details: "Invalid Value">


# Response
{'vary': 'Origin, X-Origin', 'content-type': 'application/json; charset=UTF-8', 'date': 'Thu, 18 Mar 2021 07:10:46 GMT', 'expires': 'Thu, 18 Mar 2021 07:10:46 GMT', 'cache-control': 'private, max-age=0', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'content-security-policy': "frame-ancestors 'self'", 'x-xss-protection': '1; mode=block', 'server': 'GSE', 'alt-svc': 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'transfer-encoding': 'chunked', 'status': '400', 'content-length': '226', '-content-encoding': 'gzip'}
```
I've tried to change `q` expression to:

```python
q='sharedWithMe!=true'
q='sharedWithMe=false'
q='not sharedWithMe'
q='!sharedWithMe'
```
But it didn't help.

**Comment by parthea** [comment]
Hi @mef1stofel ,

This appears to be a bug with a drive API given that this feature is mentioned in the [documentation](https://developers.google.com/drive/api/v3/ref-search-terms#file_properties). Please comment on the existing issue [here](http://issuetracker.google.com/issues/36759777) to get a status update. I've also updated the internal ticket to increase visibility of this issue. Googlers see b/173109050. I'm going to close off the issue since it is an issue with the API rather than the python client library in this Github repo.
