### ISSUE TITLE
HttpError: 'str' object has no attribute 'reason'

### ISSUE THREAD

**Issue by smarlowucf** [googleapis/google-api-python-client#1276]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Virtual environment
  - Python version: 3.8
  - pip version: 20.2.3
  - `google-api-python-client` version: 2.1.0

#### Steps to reproduce

  1. Attempt to create an HttpError

#### Code example

```python
from googleapiclient.errors import HttpError
HttpError('Not found!', content=b'Nothing')
```

#### Stack trace
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smarlow/projects/venvs/mashold/lib64/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/user/projects/venvs/env/lib64/python3.8/site-packages/googleapiclient/errors.py", line 46, in __init__
    self._get_reason()
  File "/home/user/projects/venvs/env/lib64/python3.8/site-packages/googleapiclient/errors.py", line 55, in _get_reason
    reason = self.resp.reason
AttributeError: 'str' object has no attribute 'reason'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by smarlowucf** [comment]
Sorry, this was my fault. The first argument for HttpError is expected to be a response type. :facepalm: The latest version 2.1.0 for some reason broke existing test code related to the initialization using a str instead of response.
