### ISSUE TITLE
UnknownApiNameOrVersion exception when building the cloudcommerceprocurement API

### ISSUE THREAD

**Issue by danny-zorroa** [googleapis/google-api-python-client#1284]
#### Environment details

  - OS type and version: Linux & MacOS
  - Python version: 3.7
  - pip version: 20.3
  - `google-api-python-client` version: 2.1.0

#### Steps to reproduce

  1. Attempt to build the cloudcommerceprocurement api.

#### Code example

```python
def get_procurement_api():
    return build('cloudcommerceprocurement', 'v1', cache_discovery=False,
                 credentials=get_google_credentials())
```

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/dannytiesling/zorroa/zmlp/applications/wallet/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dannytiesling/.local/share/virtualenvs/wallet-uWkrxYBm/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/dannytiesling/.local/share/virtualenvs/wallet-uWkrxYBm/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dannytiesling/.local/share/virtualenvs/wallet-uWkrxYBm/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dannytiesling/.local/share/virtualenvs/wallet-uWkrxYBm/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/dannytiesling/zorroa/zmlp/applications/wallet/app/gcpmarketplace/management/commands/gcpmarketplace-usage-report.py", line 97, in handle
    usage_reporter.report()
  File "/Users/dannytiesling/zorroa/zmlp/applications/wallet/app/gcpmarketplace/management/commands/gcpmarketplace-usage-report.py", line 22, in report
    entitlements = self._get_active_entitlements()
  File "/Users/dannytiesling/zorroa/zmlp/applications/wallet/app/gcpmarketplace/management/commands/gcpmarketplace-usage-report.py", line 31, in _get_active_entitlements
    request = get_procurement_api().providers().entitlements().list(
  File "/Users/dannytiesling/zorroa/zmlp/applications/wallet/app/gcpmarketplace/utils.py", line 16, in get_procurement_api
    credentials=get_google_credentials())
  File "/Users/dannytiesling/.local/share/virtualenvs/wallet-uWkrxYBm/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/dannytiesling/.local/share/virtualenvs/wallet-uWkrxYBm/lib/python3.7/site-packages/googleapiclient/discovery.py", line 300, in build
    static_discovery=static_discovery,
  File "/Users/dannytiesling/.local/share/virtualenvs/wallet-uWkrxYBm/lib/python3.7/site-packages/googleapiclient/discovery.py", line 405, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: cloudcommerceprocurement  version: v1
```

**Comment by danny-zorroa** [comment]
Resolved by adding `static_discovery=False` to the build function.
