### ISSUE TITLE
Directory API - Users - Delete:  Fails when using a valid user id.

### ISSUE THREAD

**Issue by Nogbit** [googleapis/google-api-python-client#1365]
I've tried each of the valid `userKey` options.  I noticed that on line 3 of my code example, the `endpoint.uri` has a `?` at the end of it...regardless of what kind of `userKey` is used.  Manually resetting that `uri` value doesn't help.

I'm using this API https://developers.google.com/admin-sdk/directory/reference/rest/v1/users/delete

#### Environment details

  - OS type and version: 
 Linux 
  - Python version: `python --version` 
 3.7.4
  - pip version: `pip --version` 
  21.1
  - `google-api-python-client` version: `pip show google-api-python-client`
Name: google-api-python-client
Version: 2.3.0
Summary: Google API Client Library for Python
Home-page: https://github.com/googleapis/google-api-python-client/
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /home/milesm/woolpert/thryv/thrv-console/.venv/lib/python3.7/site-packages
Requires: google-auth, uritemplate, httplib2, google-auth-httplib2, google-api-core, six
Required-by: 

#### Steps to reproduce

Use the `directory_v1` build.

#### Code example

```
aValidUserId = 'notarealid'
service = build('admin', 'directory_v1', credentials=validCredentials)
endpoint = service.users().delete(userKey=aValidUserId)
endpoint.execute()
```

#### API Error Response
```
'code':400
'message':'Invalid Input: userKey'
'errors':[{'message': 'Invalid Input: userKey', 'domain': 'global', 'reason': 'invalid'}]
```

#### Stack trace
```
Traceback (most recent call last):
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "./app/routers/users.py", line 199, in delete
    service.users().delete(userKey=currentUser['id']).execute()
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/milesm/testapp/.venv/lib/python3.7/site-packages/googleapiclient/http.py", line 935, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://admin.googleapis.com/admin/directory/v1/users/103777420240693602120? returned "Invalid Input: userKey". Details: "[{'message': 'Invalid Input: userKey', 'domain': 'global', 'reason': 'invalid'}]">
```

**Comment by Nogbit** [comment]
Thanks, I should of tried that first.  I get the same error there and opened a bug with them.

https://issuetracker.google.com/issues/188695462
