### ISSUE TITLE
404 when calling homegraph reportStateAndNotification

### ISSUE THREAD

**Issue by zltl** [googleapis/google-api-python-client#1475]
#### Environment details

  - OS type and version: wsl2 linux
  - Python version: `Python 3.9.6`
  - pip version: `pip 21.1.3 from /usr/lib/python3.9/site-packages/pip (python 3.9)`
  - `google-api-python-client` version: `2.15.0`

#### Steps to reproduce

 1.  Use the [Actions on Google Console](https://console.actions.google.com) to add a new smart home project.
 2. Navigate to the
[Google Cloud Console API Manager](https://console.developers.google.com/apis) . Enable the [HomeGraph API](https://console.cloud.google.com/apis/api/homegraph.googleapis.com/overview).
 3. Navigate to the [Google Cloud Console API & Services page](https://console.cloud.google.com/apis/credentials). Using role Service Account > Service Account Token Creator. Create the account and download a JSON file. Save this as `smart-home-key.json`.
 4. run python code below

#### Code example

``` python
# -*- coding: utf-8 -*-
import random
from google.oauth2 import service_account
from googleapiclient.discovery import build
import os 

rootPath = os.path.dirname(os.path.realpath(__file__))
credentials = service_account.Credentials.from_service_account_file(
        os.path.join(rootPath, 'smart-home-key.json'), 
        scopes=['https://www.googleapis.com/auth/homegraph'])
service = build('homegraph', 'v1', credentials=credentials)
obj = service.devices()
request_dict = {
    'requestId': str(random.random()),
    "agentUserId": "14711",
    "payload": {
        "devices": {
            "states": {
                "aa:01:03:11:22:cc": {
                    "on": True
                }
            },
        }
    }
}
request = service.devices().reportStateAndNotification(body=request_dict)
response = request.execute()
print("response", response)

```

#### Stack trace
```
$ python bug.py
Traceback (most recent call last):
  File "/home/ltl/smart-home-python/bug.py", line 27, in <module>
    response = request.execute()
  File "/home/ltl/.local/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ltl/.local/lib/python3.9/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://homegraph.googleapis.com/v1/devices:reportStateAndNotification?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">
```

Curl return 403, so the entity exists.
```
$ curl -XPOST https://homegraph.googleapis.com/v1/devices:reportStateAndNotification?alt=json
{
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "status": "PERMISSION_DENIED"
  }
}
```

**Comment by zltl** [comment]
my fault, device "aa:01:03:11:22:cc" not exists. closed
