### ISSUE TITLE
CustomApp publishing API is broken

### ISSUE THREAD

**Issue by sumikchakraborty** [googleapis/google-api-python-client#1510]
Environment details
OS: Linux, macOS
Python version: 2.7
API version: google-api-python-client==1.4.2

https://play.google.com/apps/publish/delegatePrivateApp? returns 404

There is no way to revert back. Previous versions took to google play console

**Comment by sumikchakraborty** [comment]
A similar issue has been fixed for google-api-ruby-client

**Comment by busunkim96** [comment]
Hi @sumikchakraborty,

Could you go into a bit more detail on the behavior you're seeing? Are you able to call `discovery.build(...)` but then all subsequent requests fail? Or do only some requests fail?

If you could link to the issue in `google-api-ruby-client` that would also be super helpful.

Thanks!

**Comment by sumikchakraborty** [comment]
@busunkim96 : The ruby api client issue is https://github.com/googleapis/google-api-ruby-client/issues/1598

The way we are trying to make a call is as follows:

 @anticipate(AfwAccountsDomainCustomAppDelegationUrlEntity, next=unicode)
    def get_app_publishing_delegation_url(self, next):
        """
        Get the URL to redirect to where enterprise Admin could
        delegate Pulse Secure Service Account to have right to publish
        custom apps.
        next (unicode): The console UI url to redirect back to after delegation.

        Returns:
            AfwAccountsDomainCustomAppDelegationUrlEntity: Redirect URL
        """
        if not self._ctx.config.GOOGLE_CUSTOM_APP_SA_CREDS or \
            not self._ctx.config.GOOGLE_CUSTOM_APP_SA_CREDS.get('client_email'):
            raise NoAfwCustomAppApiSaException(
                public_message='Missing google custom app publishing service account GOOGLE_CUSTOM_APP_SA.'
            )

        temp_token_id = binascii.hexlify(os.urandom(32))
        temp_token = TempTokenEntity(
            id=temp_token_id,
            type=CUSTOM_APP_DELEGATE_TOKEN_TYPE,
            expires=utcnow_seconds() + timedelta(days=1),
            domain_id=self._ctx.meta.auth_data.domain_id,
            action_url=CUSTOM_APP_DELEGATE_TOKEN_TYPE,
            data=dict(
                next=next
            )
        )
        self._ctx.dal.temptokens.create(temp_token)

        callback_url = api_url(
            self._ctx,
            '/api/v1/afw/domains/custom-app-delegation-callback?t=%s' % temp_token_id
        )
        url = 'https://play.google.com/apps/publish/delegatePrivateApp?%s' % \
            urlencode({
                'service_account': self._ctx.config.GOOGLE_CUSTOM_APP_SA_CREDS.get('client_email'),
                'continueUrl': callback_url,
            })

        self._log.debug(
            'Returning Google Play Custom App delegation URL for SA: %s' %
            (self._ctx.config.GOOGLE_CUSTOM_APP_SA_CREDS.get('client_email'))
        )

        return AfwAccountsDomainCustomAppDelegationUrlEntity(url=url)

------------------------------------------------------------------------------------------------------------------------------

The behaviour is as follows :- 

![Screenshot (152)](https://user-images.githubusercontent.com/42392329/132405963-d90ad22c-9c26-46e4-a207-d45dfa39a423.png)
![Screenshot (154)](https://user-images.githubusercontent.com/42392329/132405953-06eb1dbb-57b2-4c2d-adbc-9db855de368c.png)
![Screenshot (155)](https://user-images.githubusercontent.com/42392329/132405961-1883468a-5f36-4d17-9f3b-1ce4b7d5e0a0.png)

**Comment by jtwilz2021** [comment]
Hi I'm getting issues when trying to publish app on Google play console, can someone please help resolve this...

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredConstructorInternal(Native Method)
	at java.lang.Class.getConstructor0(Class.java:2329)
	at java.lang.Class.getDeclaredConstructor(Class.java:2170)
	at bitter.jnibridge.JNIBridge$a.<init>(Unknown Source:25)
	at bitter.jnibridge.JNIBridge.newInterfaceProxy(Unknown Source:8)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:83)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:237)
	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

**Comment by jtwilz2021** [comment]
This is a screen shot of the issues
![Uploading Screenshot_20211120-073916_Chrome.jpg…]()
