### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by podraco** [googleapis/google-api-python-client#1575]
#### Environment details

  - OS type and version: `"Linux raspberrypi 5.4.72-v7l+ #1354 SMP Mon Oct 19 13:39:01 BST 2020 armv7l GNU/Linux"`
  - Python version: `python --version` 3.7.3
  - pip version: `pip --version`  21.3
  - `google-api-python-client` version: `pip show google-api-python-client` 2.27.0

#### Steps to reproduce

  1. install the module via pip (either normal or virtualenv)
  2. import the module `from googleapiclient import discovery` within a file, if you use an interactive session, it wont happen.
  3. the app completely fails saying that a posixPath was parsed to pkg_utils instead of a string, since it requires the str.rstrip method at some point.
#### Code example

```python
from googleapiclient import discovery
print("success")

```

#### Stack trace
```py
Traceback (most recent call last):
  [...]
  File "EXAAMPLES/gcalendar.py", line 22, in <module>
    from googleapiclient.discovery import build
  File "VIRTUALENV/lib/python3.7/site-packages/googleapiclient/discovery.py", line 63, in <module>
    from googleapiclient.http import build_http
  File "VIRTUALENV/lib/python3.7/site-packages/googleapiclient/http.py", line 61, in <module>
    from googleapiclient.model import JsonModel
  File "VIRTUALENV/lib/python3.7/site-packages/googleapiclient/model.py", line 29, in <module>
    import pkg_resources
  File "VIRTUALENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "VIRTUALENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "VIRTUALENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3270, in _initialize_master_working_set
    for dist in working_set
  File "VIRTUALENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3270, in <genexpr>
    for dist in working_set
  File "VIRTUALENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2783, in activate
    declare_namespace(pkg)
  File "VIRTUALENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2282, in declare_namespace
    _handle_ns(packageName, path_item)
  File "VIRTUALENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2199, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 431, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1346, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1391, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
AttributeError: 'PosixPath' object has no attribute 'rstrip'

# it happens when it's importing ZOPE inside one of google's modules.
```

**Comment by sudosubin** [comment]
It looks like `google-api-python-client>=2.34.0` does not import `pkg_resources` anymore, so this issue will not occur.

**Comment by daniel-sanche** [comment]
Closing due to inactivity. If this is still a problem, please re-open and we will take a look
