### ISSUE TITLE
Unhandled depedency update: pyparsing(3.0.1)

### ISSUE THREAD

**Issue by abhishek1214** [googleapis/google-api-python-client#1579]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Linux
  - Python version: 3.7.4
  - pip version: 19.3
  - google-api-python-client==1.12.2

#### Steps to reproduce

  1. Build app

#### Code example

```python
  File "/usr/local/lib/python3.7/site-packages/httplib2/auth.py", line 20, in <module>
freelance_app |     auth_param_name = token.copy().setName("auth-param-name").addParseAction(pp.downcaseTokens)
freelance_app | AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'
```

#### Stack trace
```
Traceback (most recent call last):
freelance_app |   File "./manage.py", line 21, in <module>
freelance_app |     main()
freelance_app |   File "./manage.py", line 17, in main
freelance_app |     execute_from_command_line(sys.argv)
freelance_app |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
freelance_app |     utility.execute()
freelance_app |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
freelance_app |     django.setup()
freelance_app |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
freelance_app |     apps.populate(settings.INSTALLED_APPS)
freelance_app |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
freelance_app |     app_config.ready()
freelance_app |   File "/app/integrations/freshchat/apps.py", line 11, in ready
freelance_app |     import integrations.freshchat.receivers
freelance_app |   File "/app/integrations/freshchat/receivers.py", line 14, in <module>
freelance_app |     from integrations.freshchat import tasks
freelance_app |   File "/app/integrations/freshchat/tasks.py", line 11, in <module>
freelance_app |     from integrations.freshchat import public
freelance_app |   File "/app/integrations/freshchat/public.py", line 11, in <module>
freelance_app |     from resources.meetings import services as meeting_services
freelance_app |   File "/app/resources/meetings/services.py", line 12, in <module>
freelance_app |     from integrations.google import public
freelance_app |   File "/app/integrations/google/public.py", line 1, in <module>
freelance_app |     from integrations.google import calendar_services
freelance_app |   File "/app/integrations/google/calendar_services.py", line 4, in <module>
freelance_app |     from googleapiclient.discovery import build
freelance_app |   File "/usr/local/lib/python3.7/site-packages/googleapiclient/discovery.py", line 48, in <module>
freelance_app |     import httplib2
freelance_app |   File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 52, in <module>
freelance_app |     from . import auth
freelance_app |   File "/usr/local/lib/python3.7/site-packages/httplib2/auth.py", line 20, in <module>
freelance_app |     auth_param_name = token.copy().setName("auth-param-name").addParseAction(pp.downcaseTokens)
freelance_app | AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'
freelance_app exited with code 1

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
`httplib2` has released a new version that is compatible with pyparsing v3. https://github.com/httplib2/httplib2/issues/207 Please install `httplib2>=0.20.2`.
