### ISSUE TITLE
Error encountered while making batch call for storage.object.get 

### ISSUE THREAD

**Issue by jignesh-crest** [googleapis/google-api-python-client#2014]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Linux-CentOs8
  - Python version: Python3.10.2
  - pip version: 21.2.4
  - `google-api-python-client` version:  2.70.0

#### Code example

```python
service_batch: BatchHttpRequest = service.new_batch_http_request()

service_batch.add(
    service.objects().get(
        object="path/to/object",
        alt="media",
        bucket="bucket-1",
        userProject="project-id-123",
    ),
    callback=partial(logg, service_batch=service_batch),
)
res = service_batch.execute()

```

#### Stack trace
```
Traceback (most recent call last):
  File "/sample-sync-batch.py", line 40, in <module>
    service.objects().get(
  File "/lib/python3.10/site-packages/googleapiclient/discovery.py", line 1091, in method
    raise TypeError(
TypeError: Parameter "alt" value "media" is not an allowed value in "['json']"
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jignesh-crest** [comment]
Google API doesn't support batching for downloading or uploading requests for objects.
