### ISSUE TITLE
Adding permissions to shared drive fails sometimes

### ISSUE THREAD

**Issue by doekman** [googleapis/google-api-python-client#2072]
#### Environment details

  - OS type and version: macOS Ventura 13.2.1 (22D68)
  - Python version: Python 3.9.16
  - pip version: pip 22.1.2
  - `google-api-python-client` version: Version: 2.58.0

#### Steps to reproduce

  1. create drive services with as credentials a service account with administrator privileges
  2. create drive
  3. add group permission

When doing the third step, the call sometimes fails with the error message "The requesting user does not have the administrator privileges required to access shared drive ". This is actually not true.

I have also tried to retry the 3rd step when it fails (increasing the wait time with every step). Sometimes this works, but not always. Is this a library issue, or just some timing issue with the Google cloud?

(the actual use case is to let web users create a shared drive with predetermined permissions. In the actual code, the final step is to remove the credentials of the service account from the shared drive. I did not find a way to do this in one step)

#### Code example

* make sure the shared drive to be created does not exist.
* the trace back is from the code below, but with different constants for SERVICE_ACCOUNT_FILE/DEFAULT_SUBJECT/drive_name /organizer_email

```python
import os
from googleapiclient.discovery import build
from google.oauth2 import service_account

def build_service_credentials():
    SCOPES = ['https://www.googleapis.com/auth/drive',
        'https://www.googleapis.com/auth/admin.directory.user']
    SERVICE_ACCOUNT_FILE = 'path/to/credentials.json'
    DEFAULT_SUBJECT = 'user@domain.nl'
    service_account_file = os.path.expandvars(os.path.expanduser(SERVICE_ACCOUNT_FILE))
    service_creds = service_account.Credentials.from_service_account_file(service_account_file, scopes=SCOPES)
    return service_creds.with_subject(DEFAULT_SUBJECT)

def create_drive_with_permissions(drive_name, organizer_email):
    print(f"create_drive_with_permissions({drive_name}, {organizer_email})")
    with build('drive', 'v3', credentials= build_service_credentials()) as drive_service:
        print('# Create drive')
        response = drive_service.drives().create(requestId=f"{drive_name}", body=dict(name=drive_name)).execute()
        print(response)
        drive_id = response.get('id', None)
        print('# Add permissions')
        response = drive_service.permissions().create(fileId=drive_id,
            sendNotificationEmail=False, supportsAllDrives=True, useDomainAdminAccess=True,
            body=dict(role="organizer", type="group", emailAddress=organizer_email)).execute()
        print(response)

create_drive_with_permissions('Some_Drive_Name', 'my_group@domain.nl')
```

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/doeke/prj/ArchiBucket/aiwa/tests/./permissions.py", line 29, in <module>
    create_drive_with_permissions('00_dev-99_Testing_XXX', 'dev@archipunt.nl')
  File "/Users/doeke/prj/ArchiBucket/aiwa/tests/./permissions.py", line 24, in create_drive_with_permissions
    response = drive_service.permissions().create(fileId=drive_id,
  File "/Users/doeke/Library/Caches/pypoetry/virtualenvs/aiwa-WMuDFjQh-py3.9/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/doeke/Library/Caches/pypoetry/virtualenvs/aiwa-WMuDFjQh-py3.9/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/0AJQyRcsr775pUk9PVA/permissions?sendNotificationEmail=false&supportsAllDrives=true&useDomainAdminAccess=true&alt=json returned "The requesting user does not have the administrator privileges required to access shared drive .". Details: "[{'message': 'The requesting user does not have the administrator privileges required to access shared drive .', 'domain': 'global', 'reason': 'insufficientAdministratorPrivileges'}]">
```

**Comment by rebmcr** [comment]
I've been getting this same message (which is incorrect in my case too) when using GAM. It would appear not to be a library issue, but a Google Workspace API issue.

**Comment by doekman** [comment]
I also think it is a Google Workspace API issue, but I do not know of an other way to communicate this to Google. I only use the API for small in-house projects, so a support contract is not an option...

**Comment by rebmcr** [comment]
I think it's because of a delay after creation, before the drive ID is valid. I've managed to work around it by running a backoff-loop and retrying (with a slowly-increasing delay per loop) a request for the drive info until it succeeds, and only then trying to set the access permission.

**Comment by doekman** [comment]
Can you provide details how to backoff and retry? I retry max 5 times, and wait `0.7*try_nr` seconds between... Still get less than 50% success...

**Comment by rebmcr** [comment]
I did the retry logic manually, rather than use a library, since I was in a hurry. It can wait indefinitely with the user's permission.

`def checkDrive(id: str) -> bool:
    '''
    This function verifies that a created Google Shared Drive ID exists before indicating that it is safe to continue operations against it.
    '''
    count = 0
    wait = 10
    while True:
        if gam(f"info teamdrive {id}", js=True):
            break
        if count > wait:
            decision = input('Google Workstation API is taking a long time to handle the Shared Drive we just created. [w] continues waiting; anything else quits: ')
            if decision == 'w':
                wait += 10
            else:
                return False
        count += 1
        time.sleep((5*(math.floor(count/3)))) # 5sec delay first two tries, 10sec delay next three, 15sec delay next three, etc
    return True`

**Comment by daniel-sanche** [comment]
Closing due to inactivity. If this is still a problem, please re-open and we will take a look
