### ISSUE TITLE
`<1dev` is not a valid matcher for Python package versions in `setup.py`!

### ISSUE THREAD

**Issue by con-f-use** [googleapis/google-api-python-client#2151]
On the current master branch, you have this matcher for an `install_requires` package version in [setup.py](https://github.com/googleapis/google-api-python-client/blob/110667251e8b2c8852945bfe238f399742148cda/setup.py#L36):

```python
install_requires = [
    "httplib2>=0.15.0,<1dev",
```

The `<1dev` part is not a valid in the sense of [PEP 440](https://peps.python.org/pep-0440/) and cause problems with a number of packing tools, as seen here:

```shell
$ python -c 'from distlib.version import NormalizedMatcher; NormalizedMatcher("httplib2>=0.15.0,<1dev")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jan/.local/share/virtualenvs/master_clean-V3vlFZeD/lib/python3.7/site-packages/distlib/version.py", line 125, in __init__
    vn, prefix = self.version_class(s), False
  File "/home/jan/.local/share/virtualenvs/master_clean-V3vlFZeD/lib/python3.7/site-packages/distlib/version.py", line 33, in __init__
    self._parts = parts = self.parse(s)
  File "/home/jan/.local/share/virtualenvs/master_clean-V3vlFZeD/lib/python3.7/site-packages/distlib/version.py", line 267, in parse
    result = _normalized_key(s)
  File "/home/jan/.local/share/virtualenvs/master_clean-V3vlFZeD/lib/python3.7/site-packages/distlib/version.py", line 188, in _pep_440_key
    raise UnsupportedVersionError('Not a valid version: %s' % s)
distlib.version.UnsupportedVersionError: Not a valid version: 1dev
```

This is just speculation, but it looks like it was either faultily auto-generated by some tool, or is an incomplete copy & paste. This should be corrected and ideally the artifact files of the effected versions corrected on pypi.org.

**Comment by con-f-use** [comment]
Discussion in: https://github.com/googleapis/python-api-core/issues/504
