### ISSUE TITLE
unknown error after using pyinstaller : googleapiclient.errors.UnknownApiNameOrVersion: name: drive  version: v2

### ISSUE THREAD

**Issue by senseirenard** [googleapis/google-api-python-client#2171]
Hello, I am struggling with pydrive, I am making a simple program for uploading and sorting multiple files on a google drive, my code is working when I execute it on Spyder but after using pyinstaller to make an executable i get errors that I don't understand, if you could help me i would be very grateful ! Here is the error I get :

 
Traceback (most recent call last):
  File "app.py", line 123, in <module>
  File "pydrive\apiattr.py", line 162, in GetList
  File "pydrive\apiattr.py", line 146, in __next__
  File "pydrive\auth.py", line 57, in _decorated
  File "pydrive\auth.py", line 125, in _decorated
  File "pydrive\auth.py", line 496, in Auth
  File "pydrive\auth.py", line 523, in Authorize
  File "googleapiclient\_helpers.py", line 130, in positional_wrapper
  File "googleapiclient\discovery.py", line 287, in build
  File "googleapiclient\discovery.py", line 404, in _retrieve_discovery_doc
googleapiclient.errors.UnknownApiNameOrVersion: name: drive  version: v2
[17132] Failed to execute script 'app' due to unhandled exception!

and the line 123 of my script is : file_list = drive.ListFile({'q': "'root' in parents and trashed=false"}).GetList()

What I don't understand is why it doesn't happen when executing from Spyder and this line : "googleapiclient.errors.UnknownApiNameOrVersion: name: drive  version: v2" doesn't make sense to me

**Comment by your-data-programmer** [comment]
I came upon your post because I was encountering a similar problem. 

In comparing the build to a previous (functioning) build, I noticed that the googleapiclient folder that existed in the functioning build folder did not exist in my broken build folder.

I added the following row to the datas (list) argument of the Analysis call in my .spec file. ('C:\\[DEV ENVIRONMENT PATH]\\Lib\\site-packages\\googleapiclient\\','googleapiclient')

My built application now runs as expected.

Hopefully this will fix the issue for you also!

**Comment by senseirenard** [comment]
This couldn't fix my issue, i get the same error message but thanks to bwoodsend i have a solution : 
adding --collect-datas=googleapiclient.discovery_cache.documents to the PyInstaller command fixed the issue.
But thanks anyway for trying to help me !
