### ISSUE TITLE
Support for Chrome Webstore API

### ISSUE THREAD

**Issue by kevart** [googleapis/google-api-python-client#248]
```
scopes = ['https://www.googleapis.com/auth/chromewebstore.admin']
credentials = ServiceAccountCredentials.from_json_keyfile_name('keyfile.json', scopes=scopes)
```

oauth2client.client.HttpAccessTokenRefreshError: invalid_scope: https://www.googleapis.com/auth/chromewebstore.admin is not a valid audience string.

**Comment by jonparrott** [comment]
The scope is `https://www.googleapis.com/auth/chromewebstore`.

**Comment by kevart** [comment]
That looks better, thanks. But is _chromewebstore_ actually supported? I can't find it [here](https://developers.google.com/api-client-library/python/apis/).

Got my script working to this point:

`googleapiclient.errors.UnknownApiNameOrVersion: name: chromewebstore  version: v1.1
`

**Script:**
```
from httplib2 import Http
from apiclient.discovery import build
from oauth2client.service_account import ServiceAccountCredentials

SCOPES = ['https://www.googleapis.com/auth/chromewebstore']

credentials = ServiceAccountCredentials.from_json_keyfile_name('keyfile.json', SCOPES)
http_auth = credentials.authorize(Http())
chromewebstore = build('chromewebstore', 'v1.1', http=http_auth)


```

**Comment by jonparrott** [comment]
Hmm, I don't see to be getting that error:

```
>>> from googleapiclient import discovery
>>> discovery.build('chromewebstore', 'v1.1')
<googleapiclient.discovery.Resource object at 0x10d53c190>
```

Can you verify which version of the library you're using?

(Also, as an aside, you no longer need to construct your own http object, you can just pass `credentials=credentials` into `build`).

**Comment by kevart** [comment]
Installed with pip, should be latest.
```
pip freeze | grep google
google-api-python-client==1.5.1
```

**Comment by jonparrott** [comment]
I'm unsure why mine would work and yours wouldn't, we're on the same version.

**Comment by kevart** [comment]
I've tried again on two different machines, same result.

**Installation**
```
[ec2-user@ip-172-31-1-4 ~]$ virtualenv env
New python executable in env/bin/python2.7
Also creating executable in env/bin/python
Installing setuptools, pip...done.
[ec2-user@ip-172-31-1-4 ~]$ source env/bin/activate
(env)[ec2-user@ip-172-31-1-4 ~]$ pip install --upgrade google-api-python-client
Collecting google-api-python-client
  Downloading google_api_python_client-1.5.1-py2.py3-none-any.whl (50kB)
    100% |################################| 53kB 5.9MB/s 
Collecting six<2,>=1.6.1 (from google-api-python-client)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting uritemplate<1,>=0.6 (from google-api-python-client)
  Downloading uritemplate-0.6.tar.gz
Collecting httplib2<1,>=0.8 (from google-api-python-client)
  Downloading httplib2-0.9.2.zip (210kB)
    100% |################################| 212kB 2.2MB/s 
Collecting oauth2client (from google-api-python-client)
  Downloading oauth2client-2.2.0.tar.gz (70kB)
    100% |################################| 73kB 5.9MB/s 
Collecting simplejson>=2.5.0 (from uritemplate<1,>=0.6->google-api-python-client)
  Downloading simplejson-3.8.2.tar.gz (76kB)
    100% |################################| 77kB 5.4MB/s 
Collecting pyasn1>=0.1.7 (from oauth2client->google-api-python-client)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client->google-api-python-client)
  Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client->google-api-python-client)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |################################| 49kB 8.5MB/s 
Installing collected packages: rsa, pyasn1-modules, pyasn1, simplejson, oauth2client, httplib2, uritemplate, six, google-api-python-client

  Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c simplejson/_speedups.c -o build/temp.linux-x86_64-2.7/simplejson/_speedups.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/simplejson/_speedups.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/simplejson/_speedups.so
  Running setup.py install for oauth2client
  Running setup.py install for httplib2
  Running setup.py install for uritemplate


Successfully installed google-api-python-client-1.5.1 httplib2-0.9.2 oauth2client-2.2.0 pyasn1-0.1.9 pyasn1-modules-0.0.8 rsa-3.4.2 simplejson-3.8.2 six-1.10.0 uritemplate-0.6
```

**Script**

```
(env)[ec2-user@ip-172-31-1-4 ~]$ cat python-client.py 
# from googleapiclient import discovery  # I tried both
from apiclient import discovery
discovery.build('chromewebstore', 'v1.1')
```

**Result**
```
(env)[ec2-user@ip-172-31-1-4 ~]$ python python-client.py 
Traceback (most recent call last):
  File "python-client.py", line 3, in <module>
    discovery.build('chromewebstore', 'v1.1')
  File "/home/ec2-user/env/local/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ec2-user/env/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 218, in build
    "name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: chromewebstore  version: v1.1

```

**Comment by jonparrott** [comment]
Very weird, can you confirm that you can access it via the [API Explorer](https://developers.google.com/apis-explorer/#search/chrome%20web%20store/chromewebstore/v1.1/)?

**Comment by kevart** [comment]
That page is empty (see screenshot). It's not listed under Services either.
![screen shot 2016-07-09 at 12 51 24 pm](https://cloud.githubusercontent.com/assets/5118530/16705671/1516adfc-45d4-11e6-8991-38531b5d8309.png)

**Comment by jonparrott** [comment]
It seems that despite their being [public documentation](https://developer.chrome.com/webstore/using_webstore_api) on the webstore API, it doesn't seem to be publicly available. I'll try to investigate and see why that is.

**Comment by kevart** [comment]
Thanks! Keen to get this working.

**Comment by kevart** [comment]
Any news?

**Comment by jonparrott** [comment]
Took me a while to find the right group of people. Reaching out now. Will update when I hear back.

**Comment by kevart** [comment]
Did you hear anything?

**Comment by jonparrott** [comment]
Unfortunately it seems like my research didn't bear any fruit. It does not appear this API has an owner.

**Comment by kevart** [comment]
Do people push updates indeed manually to the chrome webstore?? That's hard to believe.

**Comment by jonparrott** [comment]
@kevart I don't use or maintain the API so I can't really say what the usage looks like. I'm sorry we couldn't help you. :(

**Comment by Jamesargy6** [comment]
Sorry to comment on such an old issue, but has any headway been made on this in the past three years? I am running into the same issue as @kevart.

**Comment by busunkim96** [comment]
@Jamesargy6 I'll try looking around again.

Could you go to https://www.googleapis.com/discovery/v1/apis and tell me if you are able to find 'chromewebstore'?

**Comment by Jamesargy6** [comment]
Thanks @busunkim96.
Unfortunately no, I do not see `chromewebstore` on that page, nor do I see it [here](https://developers.google.com/apis-explorer/).

**Comment by busunkim96** [comment]
Thanks! Could you also tell me if this page goes anywhere for you? It looks like the API isn't listed on the list, but it's possible it's still public:

https://www.googleapis.com/discovery/v1/apis/chromewebstore/v1.1/rest

**Comment by Jamesargy6** [comment]
It seems that it is not. Here's the response I get from that link:
```
// 20191030145303
// https://www.googleapis.com/discovery/v1/apis/chromewebstore/v1.1/rest

{
  "error": {
    "errors": [
      {
        "domain": "global",
        "reason": "notFound",
        "message": "Not Found"
      }
    ],
    "code": 404,
    "message": "Not Found"
  }
}

**Comment by busunkim96** [comment]
I've pinged someone on the Chrome Webstore Team to ask which parts of the API are meant to be public. Will update once I've gotten a response.

**Comment by busunkim96** [comment]
Opened internal issue 143879215

**Comment by Jamesargy6** [comment]
Thanks @busunkim96, I appreciate your following up on this.

**Comment by vesche** [comment]
@busunkim96 

Any update on this?

**Comment by busunkim96** [comment]
I pinged an engineer on the team and it looks like they are actively investigating how to make this API public. Thank you all for your patience.

**Comment by busunkim96** [comment]
Googlers see 143879215

**Comment by tcoatale** [comment]
Hi, I am also very interested in this bug fix. 
Any update @busunkim96 ?

**Comment by busunkim96** [comment]
@tcoatale I don't see any updates, but I've pinged the engineer working on the internal issue. I'll let you know when I get a response.

**Comment by busunkim96** [comment]
Update: this is still being actively worked on. Thank you all for your patience and apologies for the inconvenience!

**Comment by parthea** [comment]
I've requested an update. Googlers see b/160355251.

**Comment by sureyeaah** [comment]
Is there any update on this?

**Comment by g1zyft** [comment]
@busunkim96 any luck on this issue ?

**Comment by daniel-sanche** [comment]
This issue is being bulk closed due to inactivity. Please re-open if you think this still requires attention, and we'll take another look. Thanks!
