### ISSUE TITLE
YouTube API playlistItems can't get next page of a playlist

### ISSUE THREAD

**Issue by Mohamed5341** [googleapis/google-api-python-client#2501]
Trying to get YouTube playlist returns first page of results with 50 items while playlist total size is 849, trying to get second page leads to an error.

```Python
flow = InstalledAppFlow.from_client_secrets_file(
    <JSON_FILE>,
    scopes=[
        'https://www.googleapis.com/auth/youtube'
    ]
)

flow.run_local_server(port=8080, prompt='consent',
                      authorization_prompt_message='')
credentials = flow.credentials

youtube = build('youtube', 'v3', credentials=credentials)

playlistRequest = youtube.playlistItems().list(playlistId=<Playlist ID>, part="snippet", maxResults=50)
while playlistRequest:
    response = playlistRequest.execute()
    for item in response['items']:
        #  ... Do Something ...
    playlistRequest = youtube.playlistItems().list_next(playlistRequest, response)
```

This code was working fine before, but only yesterday it starts to give me this error.

```CMD
Traceback (most recent call last):
  File "...\....py", line ..., in <module>
    response = playlistRequest.execute()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\googleapiclient\_helpers.py", line 130, 
in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\googleapiclient\http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/playlistItems?playlistId=<Playlist ID>&part=snippet&maxResults=50&alt=json&pageToken=<Long Page ID> returned "Request contains an invalid argument.". Details: "[{'message': 'Request contains an invalid argument.', 'domain': 'global', 'reason': 'badRequest'}]">
```

I don't know why it fails getting second page, while works fine for playlist first page.

**Note:** I tried to update python library gives same error.

**Comment by Mohamed5341** [comment]
Sorry for any inconvenience, but suddenly it works.
