### ISSUE TITLE
Can't get discovery doc for API in Alpha (specifically, containeranalysis v1alpha1) as developerKey (API key) not passed

### ISSUE THREAD

**Issue by michaelbannister** [googleapis/google-api-python-client#562]
Using version 1.7.4 of this library.
I have access to the alpha of the Container Analysis feature and am trying to write some client code against the API.

```python
container_analysis = build('containeranalysis', 'v1alpha1', developerKey='***')
```
fails with:
```text
Traceback (most recent call last):
  <snip>
  File "/Users/michael/Develop/Work/commerce-platform/container-scan-notifier/main.py", line 11, in <module>
    container_analysis = build('containeranalysis', 'v1alpha1', developerKey='***')
  File "/Users/michael/.virtualenvs/container-scan-notifier-pA577bcV/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/michael/.virtualenvs/container-scan-notifier-pA577bcV/lib/python3.7/site-packages/googleapiclient/discovery.py", line 230, in build
    raise e
  File "/Users/michael/.virtualenvs/container-scan-notifier-pA577bcV/lib/python3.7/site-packages/googleapiclient/discovery.py", line 222, in build
    requested_url, discovery_http, cache_discovery, cache)
  File "/Users/michael/.virtualenvs/container-scan-notifier-pA577bcV/lib/python3.7/site-packages/googleapiclient/discovery.py", line 272, in _retrieve_discovery_doc
    raise HttpError(resp, content, uri=actual_url)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://containeranalysis.googleapis.com/$discovery/rest?version=v1alpha1 returned "The request is missing a valid API key.">
```

Testing this with `curl`, a request to `https://containeranalysis.googleapis.com/$discovery/rest?version=v1alpha1` _without_ a `key` param returns:
```json
{
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "status": "PERMISSION_DENIED"
  }
}
```
whereas adding the `key` param with my API key _does_ return the discovery document.
It looks like the `_retrieve_discovery_doc` function should accept an (optional) developerKey argument.

**Comment by hgrimberg01** [comment]
I am experience the exact same issue with another semi-public API and the above message is the cause as well.
