### ISSUE TITLE
400 "Invalid Given/Family Name: FamilyName" users().insert()

### ISSUE THREAD

**Issue by JCurtis1** [googleapis/google-api-python-client#581]
I have the following code:
```
def create_google_admin(owner: str, google_admin: str, google_admin_email: str):
    """  Create Google User profile  """

    random_password = generate_random_password()

    user_attributes = {
        'primaryEmail': google_admin_email,
        'name': {
            'givenName': owner,
            'familyName': google_admin,
        },
        'password': random_password,
        'changePasswordAtNextLogin': True,
        'orgUnitPath': '/',
        'includeInGlobalAddressList': False,
    }

    user_body = json.dumps(user_attributes)

    users_api = get_users_api()

    try:
        insert_user = users_api.insert(body=user_body).execute()    
    except HttpError as err:
        response = json.loads(err.content)
        code = response['error']['code']
        reason = response['error']['message']
        message = '{}: {}'.format(code, reason)
        sys.exit(message)

    make_google_admin()
```
Which returns the following error:
```
Traceback (most recent call last):
  File "/home/jcurtis1/.pyenv/versions/3.6.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jcurtis1/.pyenv/versions/3.6.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jcurtis1/projects/my_programs/iam-jwc/identity/work/create_google_admin.py", line 257, in <module>
    create_google_admin()
  File "/home/jcurtis1/projects/my_programs/iam-jwc/identity/work/create_google_admin.py", line 87, in create_google_admin
    insert_user = users_api.insert(body=user_body).execute()
  File "/home/jcurtis1/.pyenv/versions/my-virtual-env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/jcurtis1/.pyenv/versions/my-virtual-env/lib/python3.6/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/admin/directory/v1/users?alt=json returned "Invalid Given/Family Name: FamilyName">
```
The JSON user_body dict:
```
{"primaryEmail": "[omit]", "name": {"givenName": "[omit]", "familyName": "[omit]"}, "password": "[omit]", "changePasswordAtNextLogin": true, "orgUnitPath": "/", "includeInGlobalAddressList": false}
```
I have used the `get_users_api()` with .get() and .list() without issue.  I am authorized perform this process via:  https://developers.google.com/admin-sdk/directory/v1/reference/users/insert

I can also perform this task as expected using requests.post() using the same user_body JSON.

It appears that the constructed header of googleApiClient.http.excecute() is not `{'Content-Type': 'application/json'}` in the HTTP request.

Any help would be appreciated, as I would prefer not to rely on requests.post() call.

**Comment by busunkim96** [comment]
Hi @JCurtis1,

Would you be able to try passing `user_attributes` as the body instead of `user_body`? I think this may be related to #222.

```
def create_google_admin(owner: str, google_admin: str, google_admin_email: str):
    """  Create Google User profile  """

    random_password = generate_random_password()

    user_attributes = {
        'primaryEmail': google_admin_email,
        'name': {
            'givenName': owner,
            'familyName': google_admin,
        },
        'password': random_password,
        'changePasswordAtNextLogin': True,
        'orgUnitPath': '/',
        'includeInGlobalAddressList': False,
    }

    users_api = get_users_api()

    try:
        insert_user = users_api.insert(body=user_attributes).execute()    
    except HttpError as err:
        response = json.loads(err.content)
        code = response['error']['code']
        reason = response['error']['message']
        message = '{}: {}'.format(code, reason)
        sys.exit(message)

    make_google_admin()
```

**Comment by JCurtis1** [comment]
@sduskis Removing the json.dumps and feeding the python dictionary to body parameter resolved the issue.  Thank you.
