### ISSUE TITLE
Attempt to `pip install google-appengine` fails

### ISSUE THREAD

**Issue by seawolf42** [googleapis/google-api-python-client#607]
#### Environment details

  - OS: MacOS 10.14
  - Python version: 2.7.15 (installed with homebrew)
  - pip version: 18.1
  - `google-api-python-client` version: latest

#### Steps to reproduce

  1. `pip install google-appengine`

Output:
```bash
Collecting google-appengine
  Using cached https://files.pythonhosted.org/packages/8d/f1/405f6a85407673cd628fb29fadf84a3dd9f533551a9236609e55e04ad22c/google-appengine-1.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vd/ky1lhyn51fb5p1fqhpt85ppw0000gn/T/pip-install-HXpEVc/google-appengine/setup.py", line 2, in <module>
        import ez_setup
    ImportError: No module named ez_setup
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vd/ky1lhyn51fb5p1fqhpt85ppw0000gn/T/pip-install-HXpEVc/google-appengine/
```

**Comment by seawolf42** [comment]
Hrm, this might not be the right place for this... was not looking at the repo name when I landed here from a google search.
