### ISSUE TITLE
PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

### ISSUE THREAD

**Issue by lbatteau** [googleapis/google-api-python-client#627]
When attempting to download files from Google Drive, we are getting the following error in production.

```
[2019-02-21 09:39:35,813] ERROR in app: Exception on /api/trigger/reload [POST]
Traceback (most recent call last):
  File "./service/GDriveDownloader.py", line 127, in download_sheet
    self._download(file_path, _download_sheet)
  File "./service/GDriveDownloader.py", line 84, in _download
    items = self._list_files(folder_path, file_name)
  File "./service/GDriveDownloader.py", line 71, in _list_files
    folder_id)).execute()
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 186, in new_request
    credentials._refresh(orig_request_method)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 774, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1484, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 385, in _generate_assertion
    key_id=self._private_key_id)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 97, in make_signed_jwt
    signature = signer.sign(signing_input)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_pycrypto_crypt.py", line 99, in sign
    return PKCS1_v1_5.new(self._key).sign(SHA256.new(message))
  File "/usr/lib/python2.7/dist-packages/Crypto/Signature/PKCS1_v1_5.py", line 112, in sign
    m = self._key.decrypt(em)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 174, in decrypt
    return pubkey.pubkey.decrypt(self, ciphertext)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/pubkey.py", line 93, in decrypt
    plaintext=self._decrypt(ciphertext)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 235, in _decrypt
    r = getRandomRange(1, self.key.n-1, randfunc=self._randfunc)
  File "/usr/lib/python2.7/dist-packages/Crypto/Util/number.py", line 123, in getRandomRange
    value = getRandomInteger(bits, randfunc)
  File "/usr/lib/python2.7/dist-packages/Crypto/Util/number.py", line 104, in getRandomInteger
    S = randfunc(N>>3)
  File "/usr/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 137, in read
    self._check_pid()
  File "/usr/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 153, in _check_pid
    raise AssertionError("PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()")
```

This seems a similar issue as reported here https://github.com/GoogleCloudPlatform/gsutil/issues/390.

> So, I think most folks don't see this because it happens under a subset of runtime circumstances. We use oauth2client, which has mechanisms in place to fall back to "pure Python crypto" in the absence of pyOpenSSL -- additionally, I believe this only happens when using service account credentials. Fun.
>
> From the [PyCrypto](https://github.com/dlitz/pycrypto) docs, I think the fix here is to call `Crypto`'s `Random.atfork()` method (if `Crypto` is installed and can be imported) in the parent and child every time we spawn a new process, whether that be with `os.fork()`, `multiprocessing.Process()`, etc.:

#### Environment details

  - OS: Ubuntu 18
  - Python version: 2.7.15
  - pip version: 9.0.1
  - `google-api-python-client` version: 1.7.8

**Comment by busunkim96** [comment]
It looks like gsutil is creating new threads, and they resolved this issue by calling `Random.atfork()` before they spawned a new process. gooogleapiclient does not spawn new processes. 

Were you by chance using one `httplib2.Http()` object in multiple threads? Because `httplib2.Http() `objects are not thread safe, each thread must make requests from its own instance of `httplib2.Http()`. Here is the guide on [thread safety](https://github.com/googleapis/google-api-python-client/blob/master/docs/thread_safety.md). 

Please open a new issue if this is impacting you. Thanks!
