### ISSUE TITLE
Unclear error 403 message

### ISSUE THREAD

**Issue by michimussato** [googleapis/google-api-python-client#643]
Hi

I get the following error when trying to download a series of files from Google Drive.

`Traceback (most recent call last):
  File "/Users/michaelmussato/PycharmProjects/SyncAudio/sync_audio.py", line 187, in <module>
    main()
  File "/Users/michaelmussato/PycharmProjects/SyncAudio/sync_audio.py", line 78, in main
    status, done = downloader.next_chunk()
  File "/Users/michaelmussato/PycharmProjects/SyncAudio/venv/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/michaelmussato/PycharmProjects/SyncAudio/venv/lib/python3.6/site-packages/googleapiclient/http.py", line 705, in next_chunk
    raise HttpError(resp, content, uri=self._uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/11x5to8eh-E7mXcSAKd0-aHuvgv3kstE1?alt=media returned "The user has not granted the app 572305810469 read access to the file 11x5to8eh-E7mXcSAKd0-aHuvgv3kstE1.">
`

and when I click on the link mentioned in the traceback, I get something different...

`{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}`

I'm following the instructions outlined at https://developers.google.com/drive/api/v3/manage-downloads. How can I fix this?

**Comment by fhinkel** [comment]
Greetings, we're closing this due to inactivity. Please let us know if the issue needs to be reopened.
