### ISSUE TITLE
Issue with GMAIL API for Python2 and Python3

### ISSUE THREAD

**Issue by andreabac3** [googleapis/google-api-python-client#695]
#### Environment details

  - OS: Manjaro Linux 
  - Python version: 2.7.16
  - pip version: pip 19.0.3 from /usr/lib/python2.7/site-packages/pip (python 2.7)
  - `google-api-python-client` version: 1.7.9

#### Steps to reproduce

I have followed the guide on this link https://developers.google.com/gmail/api/quickstart/python
I run the command:
```sh
$ pip2 install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
```
I have run the software reported in the guide and I receive the following error:
```sh
Traceback (most recent call last):
  File "email.py", line 4, in <module>
    from googleapiclient.discovery import build
  File "/home/andrea/.local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 41, in <module>
    from email.generator import Generator as BytesGenerator
  File "/home/andrea/tmp/emailPython/email.py", line 4, in <module>
    from googleapiclient.discovery import build
ImportError: cannot import name build

```
The only change I made from the original guide is to specify pip2 instead of pip because in my system pip is for python3.
I also tried with  python3, I got the same error

Thank you for your attention

**Comment by busunkim96** [comment]
Hi @andreabac3, I'm not able to replicate this in a clean virtual environment. 

Could you make sure that the package is getting installed to the correct place with a `pip show`?

**Comment by busunkim96** [comment]
You can also try installing this in a virtualenv:

Please see the tutorial for more detailed instructions and explanations. [Python Packaging User Guide to virtual environments](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/)

Installing virtual env
```
python3 -m pip install --user --upgrade pip
python3 -m pip install --user virtualenv
```
Make virtualenv named `env`
```
python3 -m venv env
```

Activate the environment `env`
```
source env/bin/activate
```

Then install this library and run `email.py`.

**Comment by andreabac3** [comment]
Hi Busunkim96, 
sorry for the delay to response
I executed the procedure as you indicated for the instantiation of the new virtual environment with the python3 version.
I copied the email.py file to the new directory avoiding possible cached files.

I got the same error. I have tried with my MacBook Pro (Mojave) with python3 and the library works well.
I have attached the result obtained with the pip show command.
![DeepinScreenshot_deepin-image-viewer_20190617015429](https://user-images.githubusercontent.com/36055796/59570063-7d1a2080-9092-11e9-80f2-793341a54d33.png)

**Comment by busunkim96** [comment]
Hi Andrea, are you saying that the library works for you on your Macbook but doesn't work somewhere else?

**Comment by andreabac3** [comment]
No, I had done a mistake, I have re-tried, it's not working with my MacBook, I encountered the same error with py3 and py2.
I just have tried with classmate's computer with Arch Linux (not Manjaro) as distro and he got the same error.

All the tests are done using a new env.

**Comment by fhinkel** [comment]
Greetings, we're closing this due to inactivity. Please let us know if the issue needs to be reopened.
