### ISSUE TITLE
Google Drive copy operation reporting storage quota errors incorrectly

### ISSUE THREAD

**Issue by Spazzlo** [googleapis/google-api-python-client#707]
When a script is copying a file from a place with a file over 15 gigabytes to a place with enough space to hold that file using a service account without enough space to hold those 15 gigabytes, it errors with a storage quota error

Env Info:
```
Python 3.7
Latest client libraries
Manjaro Linux
```

Here's the code that is causing my issue. I've created a publicly readable 16 gigabyte file, so you don't have to upload 16 gigs of data yourself.
```py
from oauth2client.service_account import ServiceAccountCredentials
import googleapiclient.discovery

infile = "1-qrc07hlO6RoZ4S7wJfbO3Gs2-RreZsl" # id of a file that must be over 15G
outfolder = "out_folder_id" # id of a folder that must have a quota left over the size of the file being copied

service_account_file = "path/to/service/account.json" # credentials for an account that has view access to infile and write access to outfolder
                                          # must also not have more than 15G of quota
                                          # owner account must have google drive api enabled

credentials = ServiceAccountCredentials.from_json_keyfile_name(service_account_file, scopes=[
    "https://www.googleapis.com/auth/drive"
])

drive = googleapiclient.discovery.build("drive", "v3", credentials=credentials)

copied_file = drive.files().copy(fileId=infile, body={"parents": [outfolder]}).execute()
```

Error message:
```py
Traceback (most recent call last):
  File "storagequota.py", line 17, in <module>
    copied_file = drive.files().copy(fileId=infile, body={"parents": [outfolder]}).execute()
  File "/usr/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1-qrc07hlO6RoZ4S7wJfbO3Gs2-RreZsl/copy?alt=json returned "The user's Drive storage quota has been exceeded.">
```

**Comment by Spazzlo** [comment]
Note: I get this error with google-auth too.

**Comment by Spazzlo** [comment]
Done some testing, it's actually not your guys' problem, but it's an issue with the api itself.
