### ISSUE TITLE
Internal App Sharing support?

### ISSUE THREAD

**Issue by jacobtabak** [googleapis/google-api-python-client#711]
I am using `google-api-python-client-1.7.9`

I found [documentation](https://github.com/googleapis/google-api-python-client/blob/715bd7f9ca9a324a05ee05a6476af383e54930f9/docs/dyn/androidpublisher_v3.internalappsharingartifacts.html) for `internalappsharingartifacts` in this repo -  - but I can't figure out how to use it. It seems like the method is missing on my version of the client.

```
  File "scripts/app_sharing_upload.py", line 45, in main
    aab_response = service.internalappsharingartifacts().uploadBundle(
AttributeError: 'Resource' object has no attribute 'internalappsharingartifacts'
```

Here is some of my code for reference:

```
        service = build('androidpublisher', 'v3', http=http)
        aab_response = service.internalappsharingartifacts().uploadBundle(
            packageName=package_name,
            media_body=aab_file,
            media_mime_type=aab_file
        ).execute()
```

**Comment by busunkim96** [comment]
Apologies for the state of our documentation - you'll probably have an easier time reading it [here](http://googleapis.github.io/google-api-python-client/docs/dyn/androidpublisher_v3.html)

It looks like the method is `uploadbundle` instead of `uploadBundle`, but I'm not sure if that's what's causing the issue.


The following seems to work correctly for me:
```python
from googeapiclient import discovery

service = discovery.build('androidpublisher', 'v3')
service.internalappsharingartifacts().uploadbundle(packageName='foo').execute()
```

Would you mind showing us a bit more of your code?

**Comment by jacobtabak** [comment]
Thank you for the fast response @busunkim96 !

You're right - that's embarassing! It was a casing issue. That solved my first problem but led to another with mimeType that I will try to figure out now.

```
Traceback (most recent call last):
  File "scripts/app_sharing_upload.py", line 59, in <module>
    main()
  File "scripts/app_sharing_upload.py", line 48, in main
    media_mime_type=aab_file
  File "/Library/Python/2.7/site-packages/googleapiclient/discovery.py", line 813, in method
    if not mimeparse.best_match([media_mime_type], ','.join(accept)):
  File "/Library/Python/2.7/site-packages/googleapiclient/mimeparse.py", line 165, in best_match
    parsed_header), pos, mime_type))
  File "/Library/Python/2.7/site-packages/googleapiclient/mimeparse.py", line 94, in fitness_and_quality_parsed
    parse_media_range(mime_type)
  File "/Library/Python/2.7/site-packages/googleapiclient/mimeparse.py", line 73, in parse_media_range
    (type, subtype, params) = parse_mime_type(range)
  File "/Library/Python/2.7/site-packages/googleapiclient/mimeparse.py", line 54, in parse_mime_type
    (type, subtype) = full_type.split('/')
ValueError: too many values to unpack
```


Here is the entire script right now. 

```
#!/usr/bin/env python
import sys
#required on OSX to prevent the default 'six' library from interfering with the needed newer package,
#as of the 1.4.1 google-api library
sys.path.insert(1, '/Library/Python/2.7/site-packages')

import argparse

from googleapiclient.discovery import build
import httplib2
from oauth2client import client
from oauth2client.service_account import ServiceAccountCredentials

argparser = argparse.ArgumentParser(add_help=False)
argparser.add_argument('service_account',
                       help="Service account used to upload APK to Google Play")
argparser.add_argument('package_name',
                       help='The package name. Example: com.android.sample')
argparser.add_argument('aab_file',
                       help='The path to the AAB file to upload.')
argparser.add_argument('key_file',
                       help='The path to the p12 key file.')

def main():
    # Process flags and read their values.
    flags = argparser.parse_args()

    # Create an httplib2.Http object to handle our HTTP requests and authorize it
    # with the Credentials. Note that the first parameter, service_account_name,
    # is the Email address created for the Service account. It must be the email
    # address associated with the key that was created.
    credentials = ServiceAccountCredentials.from_p12_keyfile(
        flags.service_account,
        flags.key_file,
        scopes=['https://www.googleapis.com/auth/androidpublisher'])
    http = httplib2.Http()
    http = credentials.authorize(http)

    service = build('androidpublisher', 'v3', http=http)

    package_name = flags.package_name
    aab_file = flags.aab_file

    try:
        aab_response = service.internalappsharingartifacts().uploadbundle(
            packageName=package_name,
            media_body=aab_file,
            media_mime_type=aab_file
        ).execute()

        print 'Successfully uploaded AAB'
        print aab_response

    except client.AccessTokenRefreshError:
        print ('The credentials have been revoked or expired, please re-run the '
               'application to re-authorize')

if __name__ == '__main__':
    main()
```

**Comment by jacobtabak** [comment]
Setting `media_mime_type` to `application/octet-stream` seems to have helped. Success! Thank you.

**Comment by jacobtabak** [comment]
I'll update the script in case anyone else wants to use it.
