### ISSUE TITLE
ImportError: cannot import name 'build' from 'googleapiclient.discovery'

### ISSUE THREAD

**Issue by theflu** [googleapis/google-api-python-client#728]
Following the quickstart I get the following errors in new virtual environment.
https://developers.google.com/gmail/api/quickstart/python

Python version: 3.7.4
Windows 10
google-api-python-client-1.7.10
google-auth-httplib2-0.0.3
google-auth-oauthlib-0.4.0

```
Traceback (most recent call last):
  File ".\email.py", line 4, in <module>
    from googleapiclient.discovery import build
  File "C:\Scratch\python\test\venv\lib\site-packages\googleapiclient\discovery.py", line 32, in <module>
    from six.moves import http_client
  File "C:\Scratch\python\test\venv\lib\site-packages\six.py", line 92, in __get__
    result = self._resolve()
  File "C:\Scratch\python\test\venv\lib\site-packages\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "C:\Scratch\python\test\venv\lib\site-packages\six.py", line 82, in _import_module
    __import__(name)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Scratch\python\test\email.py", line 4, in <module>
    from googleapiclient.discovery import build
ImportError: cannot import name 'build' from 'googleapiclient.discovery' (C:\Scratch\python\test\venv\lib\site-packages\googleapiclient\discovery.py)
```

**Comment by theflu** [comment]
Naming my script email.py was interfering with pythons built in email module.
