### ISSUE TITLE
"Got an unexpected keyword argument" with valid argument

### ISSUE THREAD

**Issue by zigarn** [googleapis/google-api-python-client#733]
#### Environment details

  - OS: Ubuntu
  - Python version: 3.7.3
  - pip version: 18.1
  - `google-api-python-client` version: 1.7.10

#### Steps to reproduce

```python
from googleapiclient import discovery
service = discovery.build('photoslibrary', 'v1', credentials=credentials)
items_request = service.mediaItems().search(albumId='an_album_id')
```

Will generate this stacktrace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./.venv/lib/python3.7/site-packages/googleapiclient/discovery.py", line 715, in method
    raise TypeError('Got an unexpected keyword argument "%s"' % name)
TypeError: Got an unexpected keyword argument "albumId"
```

The problem is that the Resources's methods are built from the description https://www.googleapis.com/discovery/v1/apis/photoslibrary/v1/rest (or https://photoslibrary.googleapis.com/$discovery/rest?version=v1) and in those descriptions, there is no parameters for the 'mediaItems:search', even if the documentation says so: https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search

Thanks!

**Comment by busunkim96** [comment]
Hello! The photos API is maintained separately. Here is their [support page](https://developers.google.com/photos/library/support/how-to-get-help). The Photos API has Java and PHP client libraries, but not one for Python. You can interact with the Photos REST API via `requests` in Python.

If a Python client library is of interest, please let the Photos team know in this issue.

**Comment by k-funk** [comment]
For anyone looking for a more complete example including auth:

```
import json
import pickle
import os.path
import requests
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request


ALBUM_ID = 'put_album_id_here'

def main():
    credentialsFile = 'client_secret.json'
    pickleFile = 'token.pickle'

    SCOPES = ['https://www.googleapis.com/auth/photoslibrary.readonly']
    creds = None
    if os.path.exists(pickleFile):
        with open(pickleFile, 'rb') as token:
            creds = pickle.load(token)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                credentialsFile, SCOPES)
            creds = flow.run_local_server()
        with open(pickleFile, 'wb') as token:
            pickle.dump(creds, token)

    url = 'https://photoslibrary.googleapis.com/v1/mediaItems:search'
    payload = {'albumId': ALBUM_ID}
    headers = {
        'content-type': 'application/json',
        'Authorization': 'Bearer {}'.format(creds.token)
    }
    res = requests.post(url, data=json.dumps(payload), headers=headers)
    print(res.text)


if __name__ == '__main__':
    main()
```

**Comment by fcole90** [comment]
A more complete event which includes auth and interaction with photosevice:
```python
import os
import pickle

from google_auth_oauthlib.flow import InstalledAppFlow
# noinspection PyPackageRequirements
from google.auth.transport.requests import Request
from googleapiclient.discovery import build

# Get from env variable
FILE_PATH = 'path/to/client_secret.json'
scopes=['https://www.googleapis.com/auth/photoslibrary.appendonly']


def valid_or_authorise():
    """

    From: https://developers.google.com/people/quickstart/python


    Returns:

    """
    # The file token.pickle stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    creds = None
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                FILE_PATH, scopes)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    return creds


def photos_service():
    credentials = valid_or_authorise()
    return build(
        serviceName="photoslibrary",
        version="v1",
        credentials=credentials,
        discoveryServiceUrl="https://photoslibrary.googleapis.com/$discovery/rest?version={apiVersion}"
    )


if __name__ == "__main__":
    photos_service_ = photos_service()
    for m in filter(lambda s: not s.startswith("_"), dir(photos_service_)):
        print(f"{m}:", list(filter(lambda s: not s.startswith("_"), dir(getattr(photos_service_, m)()))))

```

**Comment by cosmincc** [comment]
For anyone else running into this who want to keep using the python client, you can patch in the missing parameters as a workaround until Google will fix it's discovery document:
```python
service = build('photoslibrary', 'v1', ...)

search_params = {
  "albumId": {
    "description": "Identifier of an album. If populated, lists all media items in specified album. Can't set in conjunction with any filters.",
    "location": "query",
    "type": "string"
  },
  "pageSize": {
    "description": "Maximum number of media items to return in the response. Fewer media items might be returned than the specified number. The default pageSize is 25, the maximum is 100."
    "location": "query",
    "type": "integer",
    "format": "int32"
  },
  "pageToken": {
    "description": "A continuation token to get the next page of the results. Adding this to the request returns the rows after the pageToken. The pageToken should be the value returned in the nextPageToken parameter in the response to the searchMediaItems request.",
    "location": "query",
    "type": "string"
  },
  "filters": {
    "description": "Filters to apply to the request. Can't be set in conjunction with an albumId.",
    "location": "query",
    "type": "object"
  }
}

service._resourceDesc['resources']['mediaItems']['methods']['search']['parameters'].update(search_params)
request = {'albumId': album_id}
service.mediaItems().search(**request).execute()
```
