### ISSUE TITLE
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/content/v2/accounts/authinfo?alt=json returned "Insufficient Permission">

### ISSUE THREAD

**Issue by castnow123** [googleapis/google-api-python-client#751]
Hi 

I tried for several days to establish a Content API connection via Python for Google Shopping but I am getting permission denied. I have been advised to post the issue here as it seems to be library specific.

1- I set up a special directory to dumpy two json files. /home/castnow2019_gmail_com/shopping-samples/content. I dumped 2 JSONs files:
client-secrets.json  merchant-info.json

2- Created a different directory that has Python code in /home/castnow2019/google/env/google-shopping/googleads-shopping-samples/python$

3- I ran pip install -r requirements.txt

4- I ran python -m shopping.content.products.list

but I received this error message:

File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/content/v2/accounts/authinfo?alt=json returned "Insufficient Permission">

how do I solve this issue?

**Comment by busunkim96** [comment]
It sounds like the credentials you are using don't have sufficient permission. Would you be able to provide a code sample?

**Comment by castnow123** [comment]
Sure..you mean Python sample code? it is here: https://github.com/googleads/googleads-shopping-samples/tree/master/python

The client-secret.json file gets created automatically by going to this link: https://console.developers.google.com/apis/credentials

**Comment by busunkim96** [comment]
@castnow123 Which sample file specifically are you running?

It looks like you are using python 2.7. Do you know which version of the client library you are using?

In addition, please review the instructions [here](https://developers.google.com/shopping-content/v2/how-tos/authorizing) and [here](https://developers.google.com/shopping-content/v2/how-tos/service-accounts) and confirm that you've followed the relevant steps for getting credentials.

**Comment by castnow123** [comment]
@busunkim96 
I am running list.py using this command python -m shopping.content.products.list

even if I run it using python3 it gives the error.

The client library is v2.1

I shared some screenshots of client-secrets.json after removing sensitive information.
this same service account is in the users section of my merchange center


![Client secrets](https://user-images.githubusercontent.com/53951768/63635407-2ca6dc80-c65a-11e9-9a57-be6ff2c3f5e2.png)

**Comment by castnow123** [comment]
@busunkim96  Yes, I am using 1.7.11 I setup OAuth2 client ID as in the screenshot attached. I named the json to client-secrets.json.

but I still rceived this error. do you have skype so I can share my screen and show you? did you try to authenticate using python and you are not getting any errors?
![client id](https://user-images.githubusercontent.com/53951768/63725753-2d569300-c853-11e9-96be-a7b98c2fe807.png)


Using application default credentials.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/castnow2019/google/env/google-shopping/googleads-shopping-samples/python/shopping/content/products/list.py", line 48, in <module>
    main(sys.argv)
  File "/home/castnow2019/google/env/google-shopping/googleads-shopping-samples/python/shopping/content/products/list.py", line 29, in main
    service, config, _ = common.init(argv, __doc__)
  File "/home/castnow2019/google/env/google-shopping/googleads-shopping-samples/python/shopping/content/common.py", line 142, in init
    retrieve_remaining_config_from_api(service, config)
  File "/home/castnow2019/google/env/google-shopping/googleads-shopping-samples/python/shopping/content/common.py", line 179, in retrieve_remaining_config_from_api
    authinfo = service.accounts().authinfo().execute()
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/content/v2/accounts/authinfo?alt=json returned "Insufficient Permission">

**Comment by castnow123** [comment]
yes I did all of the above when I wanted to authenticate using service account but that did not work too.

**Comment by HKJ96** [comment]
Hi
