### ISSUE TITLE
How to deal with “TimeoutError: [Errno 60] Operation timed out ”

### ISSUE THREAD

**Issue by Cycl-BestofBestSEO** [googleapis/google-api-python-client#789]
#### Environment details

  - OS: mac 10.14.2
  - Python version: 3.8.0
  - pip version: 19.3.1
  - `google-api-python-client` version: 1.7.11

#### Steps to reproduce

  1.  follow https://developers.google.com/webmaster-tools/search-console-api-original/v3/how-tos/search_analytics.html
  2. python3 search_analytics_api_sample.py 'https://www.aliexpress.com' '2019-12-01' '2019-12-03'   appear the question ，as follow：

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=203217488720-kmuf8umncn0jftrcgtd2bu9s4suiae58.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters.readonly&access_type=offline&response_type=code

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

Traceback (most recent call last):
  File "search_analytics_api_sample.py", line 198, in <module>
    main(sys.argv)
  File "search_analytics_api_sample.py", line 57, in main
    service, flags = sample_tools.init(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/googleapiclient/sample_tools.py", line 93, in init
    credentials = tools.run_flow(flow, storage, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/oauth2client/tools.py", line 243, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/oauth2client/client.py", line 2053, in step2_exchange
    resp, content = transport.request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/oauth2client/transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/httplib2/__init__.py", line 1948, in request
    (response, content) = self._request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/httplib2/__init__.py", line 1621, in _request
    (response, content) = self._conn_request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/httplib2/__init__.py", line 1528, in _conn_request
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/httplib2/__init__.py", line 1376, in connect
    raise socket_err
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/httplib2/__init__.py", line 1309, in connect
    sock.connect((self.host, self.port))
TimeoutError: [Errno 60] Operation timed out

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Hi @Cycl-BestofBestSEO I'm not quite sure what's happening here. It looks like the socket is timing out during the credentials exchange stage. Could you try this sample instead? it is modified to use our currently supported auth library, google-auth.

You will have to download a `credentials.json` file from the [Google Developers Console](https://console.developers.google.com/)
```python
from __future__ import print_function
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/webmasters.readonly']


def main():
    creds = None
    # The file token.pickle stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    service = build('webmasters', 'v3', credentials=creds)

    # Retrieve list of properties in account
    site_list = service.sites().list().execute()

    # Filter for verified websites
    verified_sites_urls = [s['siteUrl'] for s in site_list['siteEntry']
                        if s['permissionLevel'] != 'siteUnverifiedUser'
                            and s['siteUrl'][:4] == 'http']

    # Print the URLs of all websites you are verified for.
    for site_url in verified_sites_urls:
        print site_url
    # Retrieve list of sitemaps submitted
    sitemaps = service.sitemaps().list(siteUrl=site_url).execute()
    if 'sitemap' in sitemaps:
        sitemap_urls = [s['path'] for s in sitemaps['sitemap']]
        print "  " + "\n  ".join(sitemap_urls)




if __name__ == '__main__':
    main()
```

**Comment by busunkim96** [comment]
Closing due to lack of activity
