### ISSUE TITLE
400 error with python sample code 

### ISSUE THREAD

**Issue by shark912** [googleapis/google-api-python-client#806]
While trying to get the api set up with python I kept getting a 400 error just using the provided sample code at Google Health Trends API Starting Guide.  

The code that I am using is 
```py
#!/usr/bin/python
"""Sample code showing how to access the Google Flu Trends API."""

import csv
import datetime
import sys
import time

from googleapiclient.discovery import build

# ------ Insert your API key in the string below. -------
API_KEY = "[Key]"

SERVER = "https://www.googleapis.com"
API_VERSION = "v1beta"
DISCOVERY_URL_SUFFIX = "/discovery/v1/apis/trends/" + API_VERSION + "/rest"
DISCOVERY_URL = SERVER + DISCOVERY_URL_SUFFIX

MAX_QUERIES = 30


def DateToISOString(datestring):
    """Convert date from (eg) 'Jul 04 2004' to '2004-07-11'.
  Args:
    datestring: A date in the format 'Jul 11 2004', 'Jul 2004', or '2004'
  Returns:
    The same date in the format '2004-11-04'
  Raises:
     ValueError: when date doesn't match one of the three expected formats.
  """

    try:
        new_date = datetime.datetime.strptime(datestring, "%b %d %Y")
    except ValueError:
        try:
            new_date = datetime.datetime.strptime(datestring, "%b %Y")
        except ValueError:
            try:
                new_date = datetime.datetime.strptime(datestring, "%Y")
            except:
                raise ValueError("Date doesn't match any of '%b %d %Y', '%b %Y', '%Y'.")

    return new_date.strftime("%Y-%m-%d")


def GetQueryVolumes(
    queries, start_date, end_date, geo="US", geo_level="country", frequency="week"
):
    """Extract query volumes from Flu Trends API.
  Args:
    queries: A list of all queries to use.
    start_date: Start date for timelines, in form YYYY-MM-DD.
    end_date: End date for timelines, in form YYYY-MM-DD.
    geo: The code for the geography of interest which can be either country
         (eg "US"), region (eg "US-NY") or DMA (eg "501").
    geo_level: The granularity for the geo limitation. Can be "country",
               "region", or "dma"
    frequency: The time resolution at which to pull queries. One of "day",
               "week", "month", "year".

  Returns:
    A list of lists (one row per date) that can be output by csv.writer.

  Raises:
    ValueError: when geo_level is not one of "country", "region" or "dma".
  """

    if not API_KEY:
        raise ValueError("API_KEY not set.")

    service = build(
        "trends", API_VERSION, developerKey=API_KEY, discoveryServiceUrl=DISCOVERY_URL
    )

    dat = {}

    # Note that the API only allows querying 30 queries in one request. In
    # the event that we want to use more queries than that, we need to break
    # our request up into batches of 30.
    batch_intervals = range(0, len(queries), MAX_QUERIES)

    for batch_start in batch_intervals:
        batch_end = min(batch_start + MAX_QUERIES, len(queries))
        query_batch = queries[batch_start:batch_end]
        # Make API query
        if geo_level == "country":
            # Country format is ISO-3166-2 (2-letters), e.g. 'US'
            req = service.getTimelinesForHealth(
                terms=query_batch,
                time_startDate=start_date,
                time_endDate=end_date,
                timelineResolution=frequency,
                geoRestriction_country=geo,
            )
        elif geo_level == "dma":
            # See https://support.google.com/richmedia/answer/2745487
            req = service.getTimelinesForHealth(
                terms=query_batch,
                time_startDate=start_date,
                time_endDate=end_date,
                timelineResolution=frequency,
                geoRestriction_dma=geo,
            )
        elif geo_level == "region":
            # Region format is ISO-3166-2 (4-letters), e.g. 'US-NY' (see more examples
            # here: en.wikipedia.org/wiki/ISO_3166-2:US)
            req = service.getTimelinesForHealth(
                terms=query_batch,
                time_startDate=start_date,
                time_endDate=end_date,
                timelineResolution=frequency,
                geoRestriction_region=geo,
            )
        else:
            raise ValueError("geo_type must be one of 'country', 'region' or 'dma'")

        res = req.execute()

        # Sleep for 1 second so as to avoid hittting rate limiting.
        time.sleep(1)

        # Convert the data from the API into a dictionary of the form
        # {(query, date): count, ...}
        res_dict = {
            (line[u"term"], DateToISOString(point[u"date"])): point[u"value"]
            for line in res[u"lines"]
            for point in line[u"points"]
        }

        # Update the global results dictionary with this batch's results.
        dat.update(res_dict)

    # Make the list of lists that will be the output of the function
    res = [["date"] + queries]
    for date in sorted(list(set([x[1] for x in dat]))):
        vals = [dat.get((term, date), 0) for term in queries]
        res.append([date] + vals)

    return res


def main():
    # Examples of calling the GetQueryVolumes function for different geo
    # levels and time resolutions.
    us_weekly = GetQueryVolumes(
        ["flu", "cough"],
        start_date="2011-01-01",
        end_date="2015-01-01",
        geo="US",
        geo_level="country",
        frequency="week",
    )

    ma_region_daily = GetQueryVolumes(
        ["flu", "cough"],
        start_date="2011-01-01",
        end_date="2015-01-01",
        geo="US-MA",
        geo_level="region",
        frequency="day",
    )

    boston_dma_monthly = GetQueryVolumes(
        ["flu", "cough"],
        start_date="2011-01-01",
        end_date="2015-01-01",
        geo="506",
        geo_level="dma",
        frequency="month",
    )

    # Example of writing one of these files out as a CSV file to STDOUT.
    outwriter = csv.writer(sys.stdout)
    for row in us_weekly:
        outwriter.writerow(row)


if __name__ == "__main__":
    main()

```

and the errors that I am getting are : 

```
  Traceback (most recent call last): 
File "C:\Users\(me)\(directory name)\Lib\site-packages\test1.py", line 165, in <module>
main() 
File "C:\Users\(me)\(directory name)\Lib\site-packages\test1.py", line 137, in main us_weekly = GetQueryVolumes(['flu', 'cough'],
File "C:\Users\(me)\(directory name)\Lib\site-packages\test1.py", line 70, in GetQueryVolumes service = build('trends', 'v1beta', 
File "C:\Users\(me)\(directory name)\Lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper return wrapped(*args, **kwargs) 
File "C:\Users\(me)\(directory name)\Lib\site-packages\googleapiclient\discovery.py", line 231, in build raise e 
File "C:\Users\(me)\(directory name)\Lib\site-packages\googleapiclient\discovery.py", line 222, in build content = _retrieve_discovery_doc( 
File "C:\Users\(me)\(directory name)\Lib\site-packages\googleapiclient\discovery.py", line 276, in _retrieve_discovery_doc raise HttpError(resp, content, uri=actual_url) googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/discovery/v1/apis/trends/v1beta/rest?key=(key) returned "Bad Request">
```

From searching around on github and sites before this I've seen notes that googles documents are out of date and some use apiclient.discovery rather than the updated googleapiclient.discovery so I'm not sure how much of the getting started  guide needs to be updated  or is still relevant but I've followed it to  the best of my ability. Any help would be  greatly appreciated.

**Comment by busunkim96** [comment]
@shark912 Unfortunately it looks like this API is deprecated as it is no longer listed publicly https://www.googleapis.com/discovery/v1/apis. 

I'm not able to see the discovery doc at http://googleapis.com/discovery/v1/apis/trends/v1beta/rest, does this link work for you?

**Comment by shark912** [comment]
@busunkim96 Thank you for following up on this. I believe you're right in terms of the API being deprecated and the discovery doc link not working. I will follow-up with the Google team that I'm working with to hopefully get this resolved.

**Comment by geoffrosen** [comment]
> @shark912  "I will follow-up with the Google team that I'm working with to hopefully get this resolved."

Did you ever hear back about this?

**Comment by shark912** [comment]
@geoffrosen I attempted to communicate two times with the team, but did not hear back. I would be open to a solution if there are any, but have been using the publicly available Google Trends currently.

**Comment by geoffrosen** [comment]
@shark912 I sent them an email now. I'll update if they reply

At least some of the other methods in the API still work. I have been using the getGraph method. 

`req = service.getGraph(terms=query_batch,
                               restrictions_startDate=start_date,
                               restrictions_endDate=end_date,
                               restrictions_geo=country)`

I'm not sure if it is so different from the publicly available information. If anyone has good documentation for the API, it would be much appreciated.

**Comment by geoffrosen** [comment]
I emailed them and they fixed it. The data seems more useful (not already normalized), so might be worth it.

**Comment by shark912** [comment]
> I emailed them and they fixed it. The data seems more useful (not already normalized), so might be worth it.

@geoffrosen I'll try and follow-up with them if I have issues. Thanks for updating me,

**Comment by KarlaRehn** [comment]
@shark912 @geoffrosen Did you ever find documentation for the trends API?

**Comment by 5048721542** [comment]
Yes

**Comment by KarlaRehn** [comment]
Where?

mån 1 maj 2023 kl. 23:49 skrev 5048721542 ***@***.***>:

> Yes
>
