### ISSUE TITLE
Error: Invalid value at 'track_config.releases[0].status' when uploading to playstore

### ISSUE THREAD

**Issue by boddumanohar** [googleapis/google-api-python-client#839]
#### Environment details

  - OS:
  - Python version: Python 3.6.8
  - pip version: pip-20.0.2
  - `google-api-python-client` version: google-api-python-client-1.7.12

#### Steps to reproduce

```
    SCOPES = ['https://www.googleapis.com/auth/androidpublisher']
    CLIENT_SECRETS_FILE = 'service_account.json'
    credentials = ServiceAccountCredentials.from_json_keyfile_name(
        CLIENT_SECRETS_FILE, SCOPES)
    http = credentials.authorize(httplib2.Http())

    service = build('androidpublisher', 'v3', http=http)

    # Process flags and read their values.
    flags = argparser.parse_args()

    # Process flags and read their values.
    package_name = flags.package_name
    apk_file = flags.apk_file
    track = flags.relase_track
    version_name = flags.version_name

    try:
        edit_request = service.edits().insert(body={}, packageName=package_name)
        result = edit_request.execute()
        edit_id = result['id']

        apk_response = service.edits().apks().upload(
            editId=edit_id,
            packageName=package_name,
            media_body=apk_file).execute()

        print(f"Version code {apk_response['versionCode']} has been uploaded")

        track_response = service.edits().tracks().update(
            editId=edit_id,
            track=track,
            packageName=package_name,
            body={'releases': [{
                'name': version_name,
                'versionCodes': [str(apk_response['versionCode'])],
                'status': 'Completed',
            }]}).execute()

        print(
            f"Track {track_response['track']} is set with releases: {str(track_response['releases'])}")

        commit_request = service.edits().commit(
            editId=edit_id, packageName=package_name).execute()

        print(f"Edit: {commit_request['id']} has been committed")

    except client.AccessTokenRefreshError:
        print('The credentials have been revoked or expired, please re-run the '
              'application to re-authorize')
```

we use this piece of code to upload an apk to playstore. We have been uploading this way for the last one year without any issues. But lately we see this errror: 

```
20:35:44  Traceback (most recent call last):
20:35:44    File "publish_to_playstore.py", line 98, in <module>
20:35:44      main()
20:35:44    File "publish_to_playstore.py", line 80, in main
20:35:44      'status': 'Completed',
20:35:44    File "/usr/lib/python3.6/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
20:35:44      return wrapped(*args, **kwargs)
20:35:44    File "/usr/lib/python3.6/dist-packages/googleapiclient/http.py", line 898, in execute
20:35:44      raise HttpError(resp, content, uri=self.uri)
20:35:44  googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/androidpublisher/v3/applications/<packagename>/edits/12370503838179927217/tracks/alpha?alt=json returned "Invalid value at 'track_config.releases[0].status' (TYPE_ENUM), "Completed"". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'track_config.releases[0].status', 'description': 'Invalid value at \'track_config.releases[0].status\' (TYPE_ENUM), "Completed"'}]}]">
```

Thanks!

**Comment by snijsure** [comment]
@boddumanohar consider scrubbing url you posted above to remove your APP name and APP id.
