### ISSUE TITLE
Not Possible to set proxy while using ServiceAccount Credentials in apiclient.discovery.build

### ISSUE THREAD

**Issue by b-curn** [googleapis/google-api-python-client#851]
#### Environment details

  - OS: osx mojave
  - Python version: 3.6
  - pip version: 20.0.2
  - `google-api-python-client` version: google-api-python-client==1.8.0

#### Steps to reproduce

To reproduce, build a apiclient discovery object while passing in ServiceAccountCeredentials
and an http object. Passing in the http object is necessary to set proxy settings.

example:
```
from apiclient.discovery import build
from google.oauth2 import service_account
import os
import json
import socks
import httplib2

SCOPES = ['https://www.googleapis.com/auth/analytics.readonly']
KEY_FILE_LOCATION = '<client_secrets.json>' # Path to client_secrets.json file.
VIEW_ID = '<VIEW_ID>'

service_account_info = json.load(open(KEY_FILE_LOCATION))
credentials = service_account.Credentials.from_service_account_info(
    service_account_info)
   
http_proxy = os.getenv('http_proxy')
if http_proxy:
        host = http_proxy.split(':')[0] 
        port = int(http_proxy.split(':')[1])
        proxy_info = httplib2.ProxyInfo(socks.PROXY_TYPE_HTTP, host, port)
else:
    proxy_info = None

http = httplib2.Http(proxy_info=proxy_info)
analytics = build('analyticsreporting', 'v4', credentials=credentials, http=http)

```
result:
```
Traceback (most recent call last):
  File "get_report.py", line 91, in <module>
    main()
  File "get_report.py", line 86, in main
    analytics = initialize_analyticsreporting()
  File "get_report.py", line 35, in initialize_analyticsreporting
    analytics = build('analyticsreporting', 'v4', credentials=credentials, http=http)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery.py", line 235, in build
    client_options=client_options
  File "/Users/***/anaconda3/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery.py", line 345, in build_from_document
    raise ValueError("Arguments http and credentials are mutually exclusive.")
ValueError: Arguments http and credentials are mutually exclusive.
```

As a quick hack I went into googleapiclient.http.build_http and added in the proxy settings, and it worked fine. There may be another way to achieve this same goal but it was not immediately obvious to me.

**Comment by busunkim96** [comment]
As the error states, you cannot pass both a credentials object and an http object. If you need a custom http object, you should create an AuthorizedHttp instance.

You will need to install https://pypi.org/project/google-auth-httplib2/.

```py
from googleapiclient.http import build_http
  
authorized_http = google_auth_httplib2.AuthorizedHttp(credentials,  http=http)
analytics = build('analyticsreporting', 'v4', credentials=credentials, http=authorized_http)

```

**Comment by b-curn** [comment]
Using an AuthorizedHttpInstance gives me the following error:

```
Traceback (most recent call last):
  File "ga_download.py", line 161, in <module>
    main()
  File "ga_download.py", line 154, in main
    analytics = initialize_analyticsreporting()
  File "ga_download.py", line 42, in initialize_analyticsreporting
    analytics = build('analyticsreporting', 'v4', http=authorized_http, credentials=credentials)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery.py", line 225, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey
  File "/Users/***/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery.py", line 282, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/google/auth/credentials.py", line 124, in before_request
    self.refresh(request)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/google/oauth2/service_account.py", line 334, in refresh
    access_token, expiry, _ = _client.jwt_grant(request, self._token_uri, assertion)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/google/oauth2/_client.py", line 153, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_scope: Invalid OAuth scope or ID token audience provided.', '{"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."}')
```

I know my credentials are valid as it works normally when I don't need to go through the proxy and create the authorized_http instance.

**Comment by b-curn** [comment]
Fixed my last issue. Had to pass the scopes argument in the credential build.
````
SCOPES = ['https://www.googleapis.com/auth/analytics.readonly']
credentials = service_account.Credentials.from_service_account_info(
        service_account_info, scopes=SCOPES)
```
