### ISSUE TITLE
Python Client dont return the UserProfile info

### ISSUE THREAD

**Issue by oscarmcm** [googleapis/google-api-python-client#886]
#### Environment details

  - OS type and version: macOS 10.15
  - Python version: 3.8.1
  - pip version: 20.0.2
  - `google-api-python-client` version: 1.7.11

#### Steps to reproduce

  1. Create a simple authorization_url with `access_type='offline'`
  2. The user is redirected to the provided uri
  3. Once the user access the redirect uri, build the Google Service, with the proper tokens
  4. Call the Google service as described in the [docs](http://googleapis.github.io/google-api-python-client/docs/dyn/oauth2_v2.userinfo.html#get)
  5. The body in the response is empty.

#### Code example

```python
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
flow = Flow.from_client_config(
       GOOGLE_OAUTH_CONFIG,
       GOOGLE_OAUTH_CONFIG['scopes'],
       redirect_uri=GOOGLE_OAUTH_CONFIG['redirect_uri'],
)
flow.fetch_token(code=request.GET.get('code'))
credentials = flow.credentials
service = build('oauth2', 'v2', credentials=credentials)
service.userinfo().get().body  # Returns empty
```

#### Stack trace
```
2020-04-27 19:39:57,302 googleapiclient.discovery_cache WARNING  file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/googleapiclient/discovery_cache/__init__.py", line 42, in autodetect
    from . import file_cache
  File "env/lib/python3.8/site-packages/googleapiclient/discovery_cache/file_cache.py", line 40, in <module>
    raise ImportError(
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2020-04-27 19:36:40,997 googleapiclient.discovery INFO     URL being requested: GET https://www.googleapis.com/discovery/v1/apis/oauth2/v2/rest
2020-04-27 19:36:41,181 googleapiclient.discovery INFO     URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json
```

#### Notes

This doesnt happens if you call the API endpoint directly like this:

```python
url = 'https://www.googleapis.com/oauth2/v2/userinfo'
payload = {'alt': 'json', 'access_token': credentials.token}
response = requests.get(url, params=payload)
```

And from the stack trace it seems that the Python client is not setting correctly the parameters for the URL.

**Comment by busunkim96** [comment]
Hi,

I think what you're trying to get the userinfo for a credential. You need to add `.execute() to the end of the request. The response object is the userinfo in JSON.

```py
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build


service = build('oauth2', 'v2')
resp = service.userinfo().get().execute()
print(resp)
```

**Comment by oscarmcm** [comment]
Thanks for the help 👍 .
