### ISSUE TITLE
Conflicting google-api-core-1.21.0 vs. google-ads-python-v.5.1.0?

### ISSUE THREAD

**Issue by mbaader** [googleapis/google-api-python-client#953]
Hi,

I've successfully upgraded the google-api-python-client today to "google-api-core-1.21.0 google-api-python-client-1.9.3 protobuf-3.12.2".

After that, all of my scripts that are using the google-ads-python library started to throw a value error:

`ValueError: Specified service GoogleAdsService" does not exist in Google Ads API v3.`:

`
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.8/site-packages/google/ads/google_ads/client.py", line 233, in get_service
    service_client = getattr(api_module,
  File "/home/ec2-user/.local/lib/python3.8/site-packages/google/ads/google_ads/v3/__init__.py", line 264, in __getattr__
    module = __getattr__(util.convert_upper_case_to_snake_case(name))
  File "/home/ec2-user/.local/lib/python3.8/site-packages/google/ads/google_ads/v3/__init__.py", line 282, in __getattr__
    module = importlib.import_module(f'{_lazy_name_to_package_map[name]}.{name}')
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/.local/lib/python3.8/site-packages/google/ads/google_ads/v3/services/google_ads_service_client.py", line 24, in <module>
    import google.api_core.gapic_v1.client_info
  File "/home/ec2-user/.local/lib/python3.8/site-packages/google/api_core/gapic_v1/__init__.py", line 26, in <module>
    from google.api_core.gapic_v1 import method_async  # noqa: F401
  File "/home/ec2-user/.local/lib/python3.8/site-packages/google/api_core/gapic_v1/method_async.py", line 20, in <module>
    from google.api_core import general_helpers, grpc_helpers_async
  File "/home/ec2-user/.local/lib/python3.8/site-packages/google/api_core/grpc_helpers_async.py", line 145, in <module>
    class _WrappedStreamUnaryCall(_WrappedUnaryResponseMixin, _WrappedStreamRequestMixin, aio.StreamUnaryCall):
AttributeError: module 'grpc.experimental.aio' has no attribute 'StreamUnaryCall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./get_account_changes.py", line 137, in <module>
    main(google_ads_client, args.customer_id)
  File "./get_account_changes.py", line 67, in main
    ads_service = client.get_service('GoogleAdsService', version='v3')
  File "/home/ec2-user/.local/lib/python3.8/site-packages/google/ads/google_ads/client.py", line 236, in get_service
    raise ValueError('Specified service {}" does not exist in Google '
**ValueError: Specified service GoogleAdsService" does not exist in Google Ads API v3.`**

Is this related to the issue `[#934](https://github.com/googleapis/google-api-python-client/issues/934)`?

**Comment by busunkim96** [comment]
It doesn't look like there's any conflict in the dependencies from looking at google-ads-python's `setup.py`. 

https://github.com/googleads/google-ads-python/blob/506cba4608acb6cee9efa8a6f06070a7eb51953d/setup.py#L20-L24

```
class _WrappedStreamUnaryCall(_WrappedUnaryResponseMixin, _WrappedStreamRequestMixin, aio.StreamUnaryCall):
AttributeError: module 'grpc.experimental.aio' has no attribute 'StreamUnaryCall'
```

This error is from the `grpcio` version being too old. Could you try upgrading? `python3 -m pip install --upgrade grpcio`

**Comment by mbaader** [comment]
Hi busunkim96,

as it seems, you're right, this solved the errors. Thank you and regards
