### ISSUE TITLE
v1beta4 instances.import for cloud SQL API not working 

### ISSUE THREAD

**Issue by mizunos** [googleapis/google-api-python-client#977]
v1beta4 for cloud sql admin API- Python client I is not working and I am stumped.  The following code was deployed as a Cloud Functions using python 3.7 

```
import base64
import logging,json
from httplib2 import Http
from googleapiclient import discovery
from googleapiclient.errors import HttpError
from oauth2client.client import GoogleCredentials

PROJECT = "test-project"
INSTANCE = "testdb-instance"
DATABASE = "testdb"

def main(data,context):

  credentials = GoogleCredentials.get_application_default()
  service = discovery.build('sqladmin', 'v1beta4', http=credentials.authorize(Http()), cache_discovery=False)
  uri = "gs://{0}/{1}".format(data['bucket'], data['name'])

  instances_import_request_body = {
      "importContext" :{
          "kind": "sql#importContext",
          "fileType": "SQL",
          "uri": uri,
          "database": DATABASE,
    }
  }

  try:
      request = service.instances().import(
         project=PROJECT,
         instance=INSTANCE,
         body=instances_import_request_body)
      response = request.execute()
      print(json.dumps(response, indent=2))
  except HttpError as err:
    logging.error("cannot import DB - Reason: {}".format(err))
  else:
    logging.info("success status: {}".format(response))
```
When I try to deploy i got the following error back

```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Code in file main.py can't be loaded.
Detailed stack trace:
Traceback (most recent call last):
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 315, in check_or_load_user_function
    _function_handler.load_user_function()
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 190, in load_user_function
    spec.loader.exec_module(main_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/user_code/main.py", line xx
    request = service.instances().import(
                                       ^
SyntaxError: invalid syntax

```

If I changed the above to other method such as export or list then the code would work fine with the correct body content.
Help. - I am stucked.

**Comment by busunkim96** [comment]
Hi,

The import method is named `import_` instead of `import` since `import` is a reserved name in Python. See [documentation](http://googleapis.github.io/google-api-python-client/docs/dyn/sqladmin_v1beta4.instances.html#import_). 

In addition, please use [google-auth](https://googleapis.dev/python/google-auth/latest/user-guide.html). oauth2client was deprecated several years ago and is no longer actively maintained.

If you are in a cloud functions environment you can skip explicitly loading credentials by giving the default service account associated with the function the necessary permissions.

`discovery.build('sqladmin', 'v1beta4')` should be sufficient (you'll also need to add `google-auth` to your requirements.txt)

As for the error you're seeing,
